export const LOCALES = ['en', 'es', 'fr', 'ht', 'nl', 'pap'] as const;
export type Locale = (typeof LOCALES)[number];
export const DEFAULT_LOCALE: Locale = 'en';

export type TranslationKey =
  | 'nav.home' | 'nav.explore' | 'nav.reels' | 'nav.communities' | 'nav.messages'
  | 'nav.notifications' | 'nav.events' | 'nav.marketplace' | 'nav.saved' | 'nav.settings'
  | 'nav.creator_studio' | 'nav.business_studio' | 'nav.spotpay' | 'nav.profile'
  | 'composer.placeholder' | 'composer.photo' | 'composer.video' | 'composer.live' | 'composer.poll' | 'composer.post'
  | 'feed.for_you' | 'feed.following' | 'feed.friends' | 'feed.caribbean' | 'feed.local' | 'feed.communities' | 'feed.latest'
  | 'feed.empty' | 'feed.loading' | 'feed.error'
  | 'action.like' | 'action.comment' | 'action.share' | 'action.save' | 'action.follow' | 'action.following'
  | 'search.placeholder' | 'search.ask_caribbean'
  | 'wallet.balance' | 'wallet.top_up' | 'wallet.send' | 'wallet.payouts'
  | 'community.join' | 'community.leave' | 'community.members' | 'community.rules'
  | 'messages.empty' | 'messages.placeholder' | 'messages.send'
  | 'notifications.empty'
  | 'common.loading' | 'common.error' | 'common.retry' | 'common.cancel' | 'common.save' | 'common.delete'
  | 'common.see_more' | 'common.offline' | 'common.private';

const en: Record<TranslationKey, string> = {
  'nav.home': 'Home',
  'nav.explore': 'Explore',
  'nav.reels': 'Reels',
  'nav.communities': 'Communities',
  'nav.messages': 'Messages',
  'nav.notifications': 'Notifications',
  'nav.events': 'Events',
  'nav.marketplace': 'Marketplace',
  'nav.saved': 'Saved',
  'nav.settings': 'Settings',
  'nav.creator_studio': 'Creator Studio',
  'nav.business_studio': 'Business Studio',
  'nav.spotpay': 'SpotPay',
  'nav.profile': 'Profile',
  'composer.placeholder': "What's happening?",
  'composer.photo': 'Photo',
  'composer.video': 'Video',
  'composer.live': 'Live',
  'composer.poll': 'Poll',
  'composer.post': 'Post',
  'feed.for_you': 'For You',
  'feed.following': 'Following',
  'feed.friends': 'Friends',
  'feed.caribbean': 'Caribbean',
  'feed.local': 'Local',
  'feed.communities': 'Communities',
  'feed.latest': 'Latest',
  'feed.empty': 'Nothing here yet. Follow creators and join communities to fill your feed.',
  'feed.loading': 'Loading your feed…',
  'feed.error': 'Something went wrong loading the feed.',
  'action.like': 'Like',
  'action.comment': 'Comment',
  'action.share': 'Share',
  'action.save': 'Save',
  'action.follow': 'Follow',
  'action.following': 'Following',
  'search.placeholder': 'Search Caribbean…',
  'search.ask_caribbean': 'Ask Caribbean',
  'wallet.balance': 'Balance',
  'wallet.top_up': 'Top up',
  'wallet.send': 'Send',
  'wallet.payouts': 'Payouts',
  'community.join': 'Join',
  'community.leave': 'Leave',
  'community.members': 'Members',
  'community.rules': 'Rules',
  'messages.empty': 'No conversations yet.',
  'messages.placeholder': 'Write a message…',
  'messages.send': 'Send',
  'notifications.empty': 'You are all caught up.',
  'common.loading': 'Loading…',
  'common.error': 'Something went wrong.',
  'common.retry': 'Retry',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.see_more': 'See more',
  'common.offline': 'You are offline. Showing cached content.',
  'common.private': 'Private',
};

const es: Record<TranslationKey, string> = {
  'nav.home': 'Inicio',
  'nav.explore': 'Explorar',
  'nav.reels': 'Reels',
  'nav.communities': 'Comunidades',
  'nav.messages': 'Mensajes',
  'nav.notifications': 'Notificaciones',
  'nav.events': 'Eventos',
  'nav.marketplace': 'Mercado',
  'nav.saved': 'Guardado',
  'nav.settings': 'Configuración',
  'nav.creator_studio': 'Estudio de Creadores',
  'nav.business_studio': 'Estudio de Negocios',
  'nav.spotpay': 'SpotPay',
  'nav.profile': 'Perfil',
  'composer.placeholder': '¿Qué está pasando?',
  'composer.photo': 'Foto',
  'composer.video': 'Video',
  'composer.live': 'En vivo',
  'composer.poll': 'Encuesta',
  'composer.post': 'Publicar',
  'feed.for_you': 'Para ti',
  'feed.following': 'Siguiendo',
  'feed.friends': 'Amigos',
  'feed.caribbean': 'Caribe',
  'feed.local': 'Local',
  'feed.communities': 'Comunidades',
  'feed.latest': 'Lo último',
  'feed.empty': 'Aún no hay nada. Sigue creadores y únete a comunidades para llenar tu feed.',
  'feed.loading': 'Cargando tu feed…',
  'feed.error': 'Algo salió mal al cargar el feed.',
  'action.like': 'Me gusta',
  'action.comment': 'Comentar',
  'action.share': 'Compartir',
  'action.save': 'Guardar',
  'action.follow': 'Seguir',
  'action.following': 'Siguiendo',
  'search.placeholder': 'Buscar en el Caribe…',
  'search.ask_caribbean': 'Pregunta al Caribe',
  'wallet.balance': 'Saldo',
  'wallet.top_up': 'Recargar',
  'wallet.send': 'Enviar',
  'wallet.payouts': 'Pagos',
  'community.join': 'Unirse',
  'community.leave': 'Salir',
  'community.members': 'Miembros',
  'community.rules': 'Reglas',
  'messages.empty': 'Aún no hay conversaciones.',
  'messages.placeholder': 'Escribe un mensaje…',
  'messages.send': 'Enviar',
  'notifications.empty': 'Estás al día.',
  'common.loading': 'Cargando…',
  'common.error': 'Algo salió mal.',
  'common.retry': 'Reintentar',
  'common.cancel': 'Cancelar',
  'common.save': 'Guardar',
  'common.delete': 'Eliminar',
  'common.see_more': 'Ver más',
  'common.offline': 'Sin conexión. Mostrando contenido guardado.',
  'common.private': 'Privado',
};

const fr: Record<TranslationKey, string> = {
  'nav.home': 'Accueil',
  'nav.explore': 'Explorer',
  'nav.reels': 'Reels',
  'nav.communities': 'Communautés',
  'nav.messages': 'Messages',
  'nav.notifications': 'Notifications',
  'nav.events': 'Événements',
  'nav.marketplace': 'Marché',
  'nav.saved': 'Enregistré',
  'nav.settings': 'Paramètres',
  'nav.creator_studio': 'Studio Créateur',
  'nav.business_studio': 'Studio Business',
  'nav.spotpay': 'SpotPay',
  'nav.profile': 'Profil',
  'composer.placeholder': 'Que se passe-t-il ?',
  'composer.photo': 'Photo',
  'composer.video': 'Vidéo',
  'composer.live': 'Direct',
  'composer.poll': 'Sondage',
  'composer.post': 'Publier',
  'feed.for_you': 'Pour vous',
  'feed.following': 'Abonnements',
  'feed.friends': 'Amis',
  'feed.caribbean': 'Caraïbes',
  'feed.local': 'Local',
  'feed.communities': 'Communautés',
  'feed.latest': 'Dernières',
  'feed.empty': 'Rien ici pour le moment. Suivez des créateurs et rejoignez des communautés.',
  'feed.loading': 'Chargement de votre fil…',
  'feed.error': 'Une erreur est survenue lors du chargement du fil.',
  'action.like': "J'aime",
  'action.comment': 'Commenter',
  'action.share': 'Partager',
  'action.save': 'Enregistrer',
  'action.follow': 'Suivre',
  'action.following': 'Suivi',
  'search.placeholder': 'Rechercher dans les Caraïbes…',
  'search.ask_caribbean': 'Demander aux Caraïbes',
  'wallet.balance': 'Solde',
  'wallet.top_up': 'Recharger',
  'wallet.send': 'Envoyer',
  'wallet.payouts': 'Paiements',
  'community.join': 'Rejoindre',
  'community.leave': 'Quitter',
  'community.members': 'Membres',
  'community.rules': 'Règles',
  'messages.empty': 'Aucune conversation.',
  'messages.placeholder': 'Écrivez un message…',
  'messages.send': 'Envoyer',
  'notifications.empty': 'Vous êtes à jour.',
  'common.loading': 'Chargement…',
  'common.error': 'Une erreur est survenue.',
  'common.retry': 'Réessayer',
  'common.cancel': 'Annuler',
  'common.save': 'Enregistrer',
  'common.delete': 'Supprimer',
  'common.see_more': 'Voir plus',
  'common.offline': 'Vous êtes hors ligne. Contenu en cache affiché.',
  'common.private': 'Privé',
};

const ht: Record<TranslationKey, string> = {
  'nav.home': 'Akèy',
  'nav.explore': 'Eksplore',
  'nav.reels': 'Reels',
  'nav.communities': 'Kominote',
  'nav.messages': 'Mesaj',
  'nav.notifications': 'Notifikasyon',
  'nav.events': 'Evènman',
  'nav.marketplace': 'Mache',
  'nav.saved': 'Sere',
  'nav.settings': 'Paramèt',
  'nav.creator_studio': 'Estudio Kreyatè',
  'nav.business_studio': 'Estudio Biznis',
  'nav.spotpay': 'SpotPay',
  'nav.profile': 'Pwofil',
  'composer.placeholder': 'Kisa k ap pase ?',
  'composer.photo': 'Foto',
  'composer.video': 'Videyo',
  'composer.live': 'An dirèk',
  'composer.poll': 'Sondaj',
  'composer.post': 'Pibliye',
  'feed.for_you': 'Pou ou',
  'feed.following': 'Ap swiv',
  'feed.friends': 'Zanmi',
  'feed.caribbean': 'Karayib',
  'feed.local': 'Lokal',
  'feed.communities': 'Kominote',
  'feed.latest': 'Dènye',
  'feed.empty': 'Pa gen anyen isit. Swiv kreyatè epi rantre nan kominote.',
  'feed.loading': 'Ap chaje fil ou a…',
  'feed.error': 'Yon erè pase lè fil la ap chaje.',
  'action.like': 'Renmen',
  'action.comment': 'Kòmante',
  'action.share': 'Pataje',
  'action.save': 'Sere',
  'action.follow': 'Swiv',
  'action.following': 'Ap swiv',
  'search.placeholder': 'Chèche nan Karayib la…',
  'search.ask_caribbean': 'Mande Karayib la',
  'wallet.balance': 'Balans',
  'wallet.top_up': 'Recharje',
  'wallet.send': 'Voye',
  'wallet.payouts': 'Peman',
  'community.join': 'Rantre',
  'community.leave': 'Soti',
  'community.members': 'Manm',
  'community.rules': 'Règ',
  'messages.empty': 'Pa gen konvèsasyon.',
  'messages.placeholder': 'Ekri yon mesaj…',
  'messages.send': 'Voye',
  'notifications.empty': 'Ou a jou.',
  'common.loading': 'Ap chaje…',
  'common.error': 'Yon erè pase.',
  'common.retry': 'Eseye ankò',
  'common.cancel': 'Anile',
  'common.save': 'Sere',
  'common.delete': 'Efase',
  'common.see_more': 'Wè plis',
  'common.offline': 'Ou dekonekte. Kontni an kachèt ap afiche.',
  'common.private': 'Prive',
};

const nl: Record<TranslationKey, string> = {
  'nav.home': 'Home',
  'nav.explore': 'Ontdekken',
  'nav.reels': 'Reels',
  'nav.communities': 'Communities',
  'nav.messages': 'Berichten',
  'nav.notifications': 'Meldingen',
  'nav.events': 'Evenementen',
  'nav.marketplace': 'Marktplaats',
  'nav.saved': 'Opgeslagen',
  'nav.settings': 'Instellingen',
  'nav.creator_studio': 'Creator Studio',
  'nav.business_studio': 'Business Studio',
  'nav.spotpay': 'SpotPay',
  'nav.profile': 'Profiel',
  'composer.placeholder': 'Wat is er aan de hand?',
  'composer.photo': 'Foto',
  'composer.video': 'Video',
  'composer.live': 'Live',
  'composer.poll': 'Poll',
  'composer.post': 'Plaatsen',
  'feed.for_you': 'Voor jou',
  'feed.following': 'Volgend',
  'feed.friends': 'Vrienden',
  'feed.caribbean': 'Caribisch',
  'feed.local': 'Lokaal',
  'feed.communities': 'Communities',
  'feed.latest': 'Nieuwste',
  'feed.empty': 'Nog niets hier. Volg makers en word lid van communities.',
  'feed.loading': 'Feed laden…',
  'feed.error': 'Er ging iets mis bij het laden van de feed.',
  'action.like': 'Vind ik leuk',
  'action.comment': 'Reageren',
  'action.share': 'Delen',
  'action.save': 'Opslaan',
  'action.follow': 'Volgen',
  'action.following': 'Volgend',
  'search.placeholder': 'Zoek in het Caribisch gebied…',
  'search.ask_caribbean': 'Vraag het Cariben',
  'wallet.balance': 'Saldo',
  'wallet.top_up': 'Opwaarderen',
  'wallet.send': 'Versturen',
  'wallet.payouts': 'Uitbetalingen',
  'community.join': 'Lid worden',
  'community.leave': 'Verlaten',
  'community.members': 'Leden',
  'community.rules': 'Regels',
  'messages.empty': 'Nog geen gesprekken.',
  'messages.placeholder': 'Schrijf een bericht…',
  'messages.send': 'Versturen',
  'notifications.empty': 'Je bent helemaal bij.',
  'common.loading': 'Laden…',
  'common.error': 'Er ging iets mis.',
  'common.retry': 'Opnieuw proberen',
  'common.cancel': 'Annuleren',
  'common.save': 'Opslaan',
  'common.delete': 'Verwijderen',
  'common.see_more': 'Meer zien',
  'common.offline': 'Je bent offline. Gebufferde inhoud wordt getoond.',
  'common.private': 'Privé',
};

const pap: Record<TranslationKey, string> = {
  'nav.home': 'Kas',
  'nav.explore': 'Buska',
  'nav.reels': 'Reels',
  'nav.communities': 'Komunidat',
  'nav.messages': 'Mensah',
  'nav.notifications': 'Notifikashon',
  'nav.events': 'Eventunan',
  'nav.marketplace': 'Merka',
  'nav.saved': 'Warda',
  'nav.settings': 'Konfigurashon',
  'nav.creator_studio': 'Studio di Kreador',
  'nav.business_studio': 'Studio di Negoshi',
  'nav.spotpay': 'SpotPay',
  'nav.profile': 'Perfil',
  'composer.placeholder': 'Ki ta pasando?',
  'composer.photo': 'Fotografi',
  'composer.video': 'Video',
  'composer.live': 'En vivo',
  'composer.poll': 'Enkuesta',
  'composer.post': 'Publiká',
  'feed.for_you': 'Pa bo',
  'feed.following': 'Siguiendo',
  'feed.friends': 'Amigonan',
  'feed.caribbean': 'Karibe',
  'feed.local': 'Lokal',
  'feed.communities': 'Komunidat',
  'feed.latest': 'Mas nobo',
  'feed.empty': 'Nada aki ainda. Siguí kreadónan i drentá komunidatnan.',
  'feed.loading': 'Kargando bo feed…',
  'feed.error': 'Algo a bai mal kargando e feed.',
  'action.like': 'Ta gusta',
  'action.comment': 'Komentá',
  'action.share': 'Compartí',
  'action.save': 'Warda',
  'action.follow': 'Siguí',
  'action.following': 'Siguiendo',
  'search.placeholder': 'Buska na Karibe…',
  'search.ask_caribbean': 'Preguntá Karibe',
  'wallet.balance': 'Balans',
  'wallet.top_up': 'Karga',
  'wallet.send': 'Manda',
  'wallet.payouts': 'Pagonan',
  'community.join': 'Drentá',
  'community.leave': 'Salí',
  'community.members': 'Miembronan',
  'community.rules': 'Reglanan',
  'messages.empty': 'No tin konversashon ainda.',
  'messages.placeholder': 'Skirbi un mensah…',
  'messages.send': 'Manda',
  'notifications.empty': 'Bo ta al dia.',
  'common.loading': 'Kargando…',
  'common.error': 'Algo a bai mal.',
  'common.retry': 'Inténta otron bia',
  'common.cancel': 'Kanselá',
  'common.save': 'Warda',
  'common.delete': 'Kita',
  'common.see_more': 'Wak mas',
  'common.offline': 'Bo ta offline. Mostrando kontenido kashá.',
  'common.private': 'Privá',
};

export const dictionaries: Record<Locale, Record<TranslationKey, string>> = { en, es, fr, ht, nl, pap };

export function isLocale(value: string): value is Locale {
  return (LOCALES as readonly string[]).includes(value);
}

export function t(locale: Locale, key: TranslationKey): string {
  return dictionaries[locale]?.[key] ?? dictionaries[DEFAULT_LOCALE][key];
}

export function missingKeys(locale: Locale): TranslationKey[] {
  const reference = Object.keys(dictionaries[DEFAULT_LOCALE]) as TranslationKey[];
  return reference.filter((key) => dictionaries[locale]?.[key] === undefined);
}
