export const LOCALES = ['en', 'es', 'fr', 'ht', 'nl', 'pap'] as const;
export type Locale = (typeof LOCALES)[number];
export const DEFAULT_LOCALE: Locale = 'en';

export interface LocaleMeta {
  code: Locale;
  name: string;
  nativeName: string;
  flag: string;
  dir: 'ltr' | 'rtl';
  region: string;
}

export const LOCALE_DETAILS: Record<Locale, LocaleMeta> = {
  en: { code: 'en', name: 'English', nativeName: 'English', flag: '🌐', dir: 'ltr', region: 'Global & Caribbean' },
  es: { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇨🇺', dir: 'ltr', region: 'Cuba, RD, Puerto Rico, Caribe' },
  fr: { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇲🇶', dir: 'ltr', region: 'Martinique, Guadeloupe, Guyane, Haïti' },
  ht: { code: 'ht', name: 'Haitian Creole', nativeName: 'Kreyòl Ayisyen', flag: '🇭🇹', dir: 'ltr', region: 'Ayiti & Dyaspora' },
  nl: { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇸🇷', dir: 'ltr', region: 'Suriname, Aruba, Curaçao' },
  pap: { code: 'pap', name: 'Papiamentu', nativeName: 'Papiamentu', flag: '🇨🇼', dir: 'ltr', region: 'Aruba, Bonaire, Kòrsou' },
};

export type TranslationKey =
  | 'nav.home' | 'nav.explore' | 'nav.reels' | 'nav.communities' | 'nav.messages'
  | 'nav.notifications' | 'nav.events' | 'nav.marketplace' | 'nav.saved' | 'nav.settings'
  | 'nav.creator_studio' | 'nav.business_studio' | 'nav.payments' | 'nav.profile'
  | 'nav.reels_shorts' | 'nav.sounds' | 'nav.live_streams' | 'nav.podcasts'
  | 'nav.cultural_events' | 'nav.pages_stores' | 'nav.financial_center' | 'nav.map' | 'nav.create_hub' | 'nav.sign_in'
  | 'composer.placeholder' | 'composer.photo' | 'composer.video' | 'composer.live' | 'composer.poll' | 'composer.post'
  | 'feed.for_you' | 'feed.following' | 'feed.friends' | 'feed.caribbean' | 'feed.local' | 'feed.communities' | 'feed.latest'
  | 'feed.empty' | 'feed.loading' | 'feed.error'
  | 'action.like' | 'action.comment' | 'action.share' | 'action.save' | 'action.follow' | 'action.following'
  | 'search.placeholder' | 'search.ask_caribbean'
  | 'wallet.balance' | 'wallet.top_up' | 'wallet.send' | 'wallet.payouts'
  | 'community.join' | 'community.leave' | 'community.members' | 'community.rules'
  | 'messages.empty' | 'messages.placeholder' | 'messages.send'
  | 'notifications.empty'
  | 'post.translate' | 'post.show_original' | 'post.translating' | 'post.translated_from'
  | 'post.translation_unavailable' | 'post.report' | 'post.repost' | 'post.tip_creator'
  | 'settings.language' | 'settings.language_title' | 'settings.language_description' | 'settings.language_updated'
  | 'settings.save_changes' | 'settings.account' | 'settings.privacy' | 'settings.notifications'
  | 'onboarding.choose_language' | 'onboarding.language_subtitle' | 'onboarding.welcome'
  | 'onboarding.identity_title' | 'onboarding.identity_subtitle' | 'onboarding.search_roots'
  | 'onboarding.diaspora_question' | 'onboarding.continue'
  | 'marketplace.title' | 'marketplace.search' | 'marketplace.buy_now' | 'marketplace.add_to_cart' | 'marketplace.out_of_stock'
  | 'a11y.open_menu' | 'a11y.close' | 'a11y.search'
  | 'time.just_now' | 'time.minutes_ago' | 'time.hours_ago' | 'time.days_ago'
  | 'common.loading' | 'common.error' | 'common.retry' | 'common.cancel' | 'common.save' | 'common.delete'
  | 'common.see_more' | 'common.offline' | 'common.private'
  | 'gateway.tagline' | 'gateway.hero_title_1' | 'gateway.hero_connected' | 'gateway.hero_empowered'
  | 'gateway.hero_subtitle' | 'gateway.join_tukubi' | 'gateway.create_account' | 'gateway.spotlight'
  | 'auth.welcome_back' | 'auth.signin_subtitle' | 'auth.email_label' | 'auth.password_label'
  | 'auth.remember_me' | 'auth.forgot_password' | 'auth.dont_have_account' | 'auth.sign_in'
  | 'nav.economy_culture' | 'nav.explore_connect' | 'nav.people_creators' | 'nav.view_all_results';

const en: Record<TranslationKey, string> = {
  'nav.home': 'Home',
  'nav.explore': 'Explore',
  'nav.reels': 'Reels',
  'nav.communities': 'Communities',
  'nav.messages': 'Messages',
  'nav.notifications': 'Notifications',
  'nav.events': 'Events',
  'nav.marketplace': 'Marketplace',
  'nav.saved': 'Saved',
  'nav.settings': 'Settings',
  'nav.creator_studio': 'Creator Studio',
  'nav.business_studio': 'Business Studio',
  'nav.payments': 'Payments',
  'nav.profile': 'Profile',
  'nav.reels_shorts': 'Reels & Shorts',
  'nav.sounds': 'Caribbean Sounds',
  'nav.live_streams': 'Live Streams',
  'nav.podcasts': 'Podcasts Network',
  'nav.cultural_events': 'Cultural Events',
  'nav.pages_stores': 'Pages & Stores',
  'nav.financial_center': 'Financial Center',
  'nav.map': 'Caribbean Map',
  'nav.create_hub': 'Create Hub',
  'nav.sign_in': 'Sign In',
  'composer.placeholder': "What's happening?",
  'composer.photo': 'Photo',
  'composer.video': 'Video',
  'composer.live': 'Live',
  'composer.poll': 'Poll',
  'composer.post': 'Post',
  'feed.for_you': 'For You',
  'feed.following': 'Following',
  'feed.friends': 'Friends',
  'feed.caribbean': 'Caribbean',
  'feed.local': 'Local',
  'feed.communities': 'Communities',
  'feed.latest': 'Latest',
  'feed.empty': 'Nothing here yet. Follow creators and join communities to fill your feed.',
  'feed.loading': 'Loading your feed…',
  'feed.error': 'Something went wrong loading the feed.',
  'action.like': 'Like',
  'action.comment': 'Comment',
  'action.share': 'Share',
  'action.save': 'Save',
  'action.follow': 'Follow',
  'action.following': 'Following',
  'search.placeholder': 'Search Caribbean…',
  'search.ask_caribbean': 'Ask Caribbean',
  'wallet.balance': 'Balance',
  'wallet.top_up': 'Top up',
  'wallet.send': 'Send',
  'wallet.payouts': 'Payouts',
  'community.join': 'Join',
  'community.leave': 'Leave',
  'community.members': 'Members',
  'community.rules': 'Rules',
  'messages.empty': 'No conversations yet.',
  'messages.placeholder': 'Write a message…',
  'messages.send': 'Send',
  'notifications.empty': 'You are all caught up.',
  'post.translate': 'Translate to {lang}',
  'post.show_original': 'Show original',
  'post.translating': 'Translating…',
  'post.translated_from': 'Translated from {lang}',
  'post.translation_unavailable': 'Translation temporarily unavailable.',
  'post.report': 'Report Content',
  'post.repost': 'Repost',
  'post.tip_creator': 'Tip Creator',
  'settings.language': 'Language',
  'settings.language_title': 'Language & Region',
  'settings.language_description': 'Select your preferred language for the TUKUBI platform.',
  'settings.language_updated': 'Language preference saved.',
  'settings.save_changes': 'Save Changes',
  'settings.account': 'Account',
  'settings.privacy': 'Privacy',
  'settings.notifications': 'Notifications',
  'onboarding.choose_language': 'Choose your language',
  'onboarding.language_subtitle': 'Select your preferred language. You can change this at any time in Settings.',
  'onboarding.welcome': 'Welcome to TUKUBI',
  'onboarding.identity_title': 'Identity Setup',
  'onboarding.identity_subtitle': 'To personalize your cultural feeds and connect with your diaspora, select your Caribbean roots.',
  'onboarding.search_roots': 'Search all 30+ islands and territories…',
  'onboarding.diaspora_question': 'Are you living outside your home territory (Diaspora)?',
  'onboarding.continue': 'Continue',
  'marketplace.title': 'Marketplace',
  'marketplace.search': 'Search marketplace…',
  'marketplace.buy_now': 'Buy Now',
  'marketplace.add_to_cart': 'Add to Cart',
  'marketplace.out_of_stock': 'Out of stock',
  'a11y.open_menu': 'Open menu',
  'a11y.close': 'Close',
  'a11y.search': 'Search',
  'time.just_now': 'Just now',
  'time.minutes_ago': '{count}m ago',
  'time.hours_ago': '{count}h ago',
  'time.days_ago': '{count}d ago',
  'common.loading': 'Loading…',
  'common.error': 'Something went wrong.',
  'common.retry': 'Retry',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.see_more': 'See more',
  'common.offline': 'You are offline. Showing cached content.',
  'common.private': 'Private',
  'gateway.tagline': 'One Caribbean. One Community. One Digital Home.',
  'gateway.hero_title_1': 'Your Caribbean.',
  'gateway.hero_connected': 'Connected.',
  'gateway.hero_empowered': 'Empowered.',
  'gateway.hero_subtitle': 'The Caribbean and its global diaspora united in one platform to connect with family & culture, create content, discover commerce, and thrive.',
  'gateway.join_tukubi': 'Join Tukubi',
  'gateway.create_account': 'Create your account',
  'gateway.spotlight': 'Caribbean Spotlight',
  'auth.welcome_back': 'Welcome back',
  'auth.signin_subtitle': 'Sign in to TUKUBI — The Caribbean Connected.',
  'auth.email_label': 'Email or phone',
  'auth.password_label': 'Password',
  'auth.remember_me': 'Remember me',
  'auth.forgot_password': 'Forgot password?',
  'auth.dont_have_account': "Don't have an account?",
  'auth.sign_in': 'Sign In',
  'nav.economy_culture': 'Economy & Culture',
  'nav.explore_connect': 'Explore & Connect',
  'nav.people_creators': 'People & Creators',
  'nav.view_all_results': 'View All Results →',
};

const es: Record<TranslationKey, string> = {
  'nav.home': 'Inicio',
  'nav.explore': 'Explorar',
  'nav.reels': 'Reels',
  'nav.communities': 'Comunidades',
  'nav.messages': 'Mensajes',
  'nav.notifications': 'Notificaciones',
  'nav.events': 'Eventos',
  'nav.marketplace': 'Mercado',
  'nav.saved': 'Guardado',
  'nav.settings': 'Configuración',
  'nav.creator_studio': 'Estudio de Creadores',
  'nav.business_studio': 'Estudio de Negocios',
  'nav.payments': 'Pagos',
  'nav.profile': 'Perfil',
  'nav.reels_shorts': 'Reels y Cortos',
  'nav.sounds': 'Sonidos del Caribe',
  'nav.live_streams': 'Transmisiones en Vivo',
  'nav.podcasts': 'Red de Podcasts',
  'nav.cultural_events': 'Eventos Culturales',
  'nav.pages_stores': 'Páginas y Tiendas',
  'nav.financial_center': 'Centro Financiero',
  'nav.map': 'Mapa del Caribe',
  'nav.create_hub': 'Crear Centro',
  'nav.sign_in': 'Iniciar Sesión',
  'composer.placeholder': '¿Qué está pasando?',
  'composer.photo': 'Foto',
  'composer.video': 'Video',
  'composer.live': 'En vivo',
  'composer.poll': 'Encuesta',
  'composer.post': 'Publicar',
  'feed.for_you': 'Para ti',
  'feed.following': 'Siguiendo',
  'feed.friends': 'Amigos',
  'feed.caribbean': 'Caribe',
  'feed.local': 'Local',
  'feed.communities': 'Comunidades',
  'feed.latest': 'Lo último',
  'feed.empty': 'Aún no hay nada. Sigue creadores y únete a comunidades para llenar tu feed.',
  'feed.loading': 'Cargando tu feed…',
  'feed.error': 'Algo salió mal al cargar el feed.',
  'action.like': 'Me gusta',
  'action.comment': 'Comentar',
  'action.share': 'Compartir',
  'action.save': 'Guardar',
  'action.follow': 'Seguir',
  'action.following': 'Siguiendo',
  'search.placeholder': 'Buscar en el Caribe…',
  'search.ask_caribbean': 'Pregunta al Caribe',
  'wallet.balance': 'Saldo',
  'wallet.top_up': 'Recargar',
  'wallet.send': 'Enviar',
  'wallet.payouts': 'Pagos',
  'community.join': 'Unirse',
  'community.leave': 'Salir',
  'community.members': 'Miembros',
  'community.rules': 'Reglas',
  'messages.empty': 'Aún no hay conversaciones.',
  'messages.placeholder': 'Escribe un mensaje…',
  'messages.send': 'Enviar',
  'notifications.empty': 'Estás al día.',
  'post.translate': 'Traducir al {lang}',
  'post.show_original': 'Mostrar original',
  'post.translating': 'Traduciendo…',
  'post.translated_from': 'Traducido del {lang}',
  'post.translation_unavailable': 'Traducción no disponible temporalmente.',
  'post.report': 'Reportar Contenido',
  'post.repost': 'Republicar',
  'post.tip_creator': 'Dar Propina',
  'settings.language': 'Idioma',
  'settings.language_title': 'Idioma y Región',
  'settings.language_description': 'Selecciona tu idioma preferido para la plataforma TUKUBI.',
  'settings.language_updated': 'Preferencia de idioma guardada.',
  'settings.save_changes': 'Guardar Cambios',
  'settings.account': 'Cuenta',
  'settings.privacy': 'Privacidad',
  'settings.notifications': 'Notificaciones',
  'onboarding.choose_language': 'Elige tu idioma',
  'onboarding.language_subtitle': 'Selecciona tu idioma preferido. Puedes cambiarlo en cualquier momento en Configuración.',
  'onboarding.welcome': 'Bienvenido a TUKUBI',
  'onboarding.identity_title': 'Configuración de Identidad',
  'onboarding.identity_subtitle': 'Para personalizar tus feeds culturales y conectar con tu diáspora, selecciona tus raíces caribeñas.',
  'onboarding.search_roots': 'Buscar entre más de 30 islas y territorios…',
  'onboarding.diaspora_question': '¿Vives fuera de tu territorio natal (Diáspora)?',
  'onboarding.continue': 'Continuar',
  'marketplace.title': 'Mercado',
  'marketplace.search': 'Buscar en el mercado…',
  'marketplace.buy_now': 'Comprar Ahora',
  'marketplace.add_to_cart': 'Añadir al Carrito',
  'marketplace.out_of_stock': 'Agotado',
  'a11y.open_menu': 'Abrir menú',
  'a11y.close': 'Cerrar',
  'a11y.search': 'Buscar',
  'time.just_now': 'Hace un momento',
  'time.minutes_ago': 'Hace {count}m',
  'time.hours_ago': 'Hace {count}h',
  'time.days_ago': 'Hace {count}d',
  'common.loading': 'Cargando…',
  'common.error': 'Algo salió mal.',
  'common.retry': 'Reintentar',
  'common.cancel': 'Cancelar',
  'common.save': 'Guardar',
  'common.delete': 'Eliminar',
  'common.see_more': 'Ver más',
  'common.offline': 'Sin conexión. Mostrando contenido guardado.',
  'common.private': 'Privado',
  'gateway.tagline': 'Un Caribe. Una Comunidad. Un Hogar Digital.',
  'gateway.hero_title_1': 'Tu Caribe.',
  'gateway.hero_connected': 'Conectado.',
  'gateway.hero_empowered': 'Empoderado.',
  'gateway.hero_subtitle': 'El Caribe y su diáspora global unidos en una sola plataforma para conectar con familia y cultura, crear contenido, descubrir comercio y prosperar.',
  'gateway.join_tukubi': 'Unirse a Tukubi',
  'gateway.create_account': 'Crear Cuenta',
  'gateway.spotlight': 'Destacado del Caribe',
  'auth.welcome_back': 'Bienvenido de nuevo',
  'auth.signin_subtitle': 'Inicia sesión en TUKUBI — El Caribe Conectado.',
  'auth.email_label': 'Correo electrónico o teléfono',
  'auth.password_label': 'Contraseña',
  'auth.remember_me': 'Recordarme',
  'auth.forgot_password': '¿Olvidaste tu contraseña?',
  'auth.dont_have_account': '¿No tienes una cuenta?',
  'auth.sign_in': 'Iniciar Sesión',
  'nav.economy_culture': 'Economía y Cultura',
  'nav.explore_connect': 'Explorar y Conectar',
  'nav.people_creators': 'Personas y Creadores',
  'nav.view_all_results': 'Ver Todos los Resultados →',
};

const fr: Record<TranslationKey, string> = {
  'nav.home': 'Accueil',
  'nav.explore': 'Explorer',
  'nav.reels': 'Reels',
  'nav.communities': 'Communautés',
  'nav.messages': 'Messages',
  'nav.notifications': 'Notifications',
  'nav.events': 'Événements',
  'nav.marketplace': 'Marché',
  'nav.saved': 'Enregistré',
  'nav.settings': 'Paramètres',
  'nav.creator_studio': 'Studio Créateur',
  'nav.business_studio': 'Studio Business',
  'nav.payments': 'Paiements',
  'nav.profile': 'Profil',
  'nav.reels_shorts': 'Reels & Courts',
  'nav.sounds': 'Sons des Caraïbes',
  'nav.live_streams': 'Diffusions en Direct',
  'nav.podcasts': 'Réseau de Podcasts',
  'nav.cultural_events': 'Événements Culturels',
  'nav.pages_stores': 'Pages & Boutiques',
  'nav.financial_center': 'Centre Financier',
  'nav.map': 'Carte des Caraïbes',
  'nav.create_hub': 'Créer un Hub',
  'nav.sign_in': 'Se connecter',
  'composer.placeholder': 'Que se passe-t-il ?',
  'composer.photo': 'Photo',
  'composer.video': 'Vidéo',
  'composer.live': 'Direct',
  'composer.poll': 'Sondage',
  'composer.post': 'Publier',
  'feed.for_you': 'Pour vous',
  'feed.following': 'Abonnements',
  'feed.friends': 'Amis',
  'feed.caribbean': 'Caraïbes',
  'feed.local': 'Local',
  'feed.communities': 'Communautés',
  'feed.latest': 'Dernières',
  'feed.empty': 'Rien ici pour le moment. Suivez des créateurs et rejoignez des communautés.',
  'feed.loading': 'Chargement de votre fil…',
  'feed.error': 'Une erreur est survenue lors du chargement du fil.',
  'action.like': "J'aime",
  'action.comment': 'Commenter',
  'action.share': 'Partager',
  'action.save': 'Enregistrer',
  'action.follow': 'Suivre',
  'action.following': 'Suivi',
  'search.placeholder': 'Rechercher dans les Caraïbes…',
  'search.ask_caribbean': 'Demander aux Caraïbes',
  'wallet.balance': 'Solde',
  'wallet.top_up': 'Recharger',
  'wallet.send': 'Envoyer',
  'wallet.payouts': 'Paiements',
  'community.join': 'Rejoindre',
  'community.leave': 'Quitter',
  'community.members': 'Membres',
  'community.rules': 'Règles',
  'messages.empty': 'Aucune conversation.',
  'messages.placeholder': 'Écrivez un message…',
  'messages.send': 'Envoyer',
  'notifications.empty': 'Vous êtes à jour.',
  'post.translate': 'Traduire en {lang}',
  'post.show_original': "Afficher l'original",
  'post.translating': 'Traduction en cours…',
  'post.translated_from': 'Traduit du {lang}',
  'post.translation_unavailable': 'Traduction temporairement indisponible.',
  'post.report': 'Signaler le contenu',
  'post.repost': 'Repartager',
  'post.tip_creator': 'Pourboire créateur',
  'settings.language': 'Langue',
  'settings.language_title': 'Langue & Région',
  'settings.language_description': 'Sélectionnez votre langue préférée pour la plateforme TUKUBI.',
  'settings.language_updated': 'Préférence de langue enregistrée.',
  'settings.save_changes': 'Enregistrer les modifications',
  'settings.account': 'Compte',
  'settings.privacy': 'Confidentialité',
  'settings.notifications': 'Notifications',
  'onboarding.choose_language': 'Choisissez votre langue',
  'onboarding.language_subtitle': 'Sélectionnez votre langue préférée. Vous pouvez la modifier à tout moment dans Paramètres.',
  'onboarding.welcome': 'Bienvenue sur TUKUBI',
  'onboarding.identity_title': 'Configuration de l’identité',
  'onboarding.identity_subtitle': 'Pour personnaliser vos fils culturels et vous connecter à votre diaspora, sélectionnez vos origines caribéennes.',
  'onboarding.search_roots': 'Rechercher parmi plus de 30 îles et territoires…',
  'onboarding.diaspora_question': 'Vivez-vous hors de votre territoire d’origine (Diaspora) ?',
  'onboarding.continue': 'Continuer',
  'marketplace.title': 'Marché',
  'marketplace.search': 'Rechercher sur le marché…',
  'marketplace.buy_now': 'Acheter maintenant',
  'marketplace.add_to_cart': 'Ajouter au panier',
  'marketplace.out_of_stock': 'Rupture de stock',
  'a11y.open_menu': 'Ouvrir le menu',
  'a11y.close': 'Fermer',
  'a11y.search': 'Rechercher',
  'time.just_now': 'À l’instant',
  'time.minutes_ago': 'Il y a {count}m',
  'time.hours_ago': 'Il y a {count}h',
  'time.days_ago': 'Il y a {count}j',
  'common.loading': 'Chargement…',
  'common.error': 'Une erreur est survenue.',
  'common.retry': 'Réessayer',
  'common.cancel': 'Annuler',
  'common.save': 'Enregistrer',
  'common.delete': 'Supprimer',
  'common.see_more': 'Voir plus',
  'common.offline': 'Vous êtes hors ligne. Contenu en cache affiché.',
  'common.private': 'Privé',
  'gateway.tagline': 'Une Caraïbe. Une Communauté. Un Foyer Numérique.',
  'gateway.hero_title_1': 'Vos Caraïbes.',
  'gateway.hero_connected': 'Connectées.',
  'gateway.hero_empowered': 'Autonomisées.',
  'gateway.hero_subtitle': 'La Caraïbe et sa diaspora mondiale unies sur une seule plateforme pour se connecter avec la famille et la culture, créer du contenu, découvrir le commerce et prospérer.',
  'gateway.join_tukubi': 'Rejoindre Tukubi',
  'gateway.create_account': 'Créer un Compte',
  'gateway.spotlight': 'Pleins feux sur les Caraïbes',
  'auth.welcome_back': 'Bon retour',
  'auth.signin_subtitle': 'Connectez-vous à TUKUBI — Les Caraïbes Connectées.',
  'auth.email_label': 'E-mail ou téléphone',
  'auth.password_label': 'Mot de passe',
  'auth.remember_me': 'Se souvenir de moi',
  'auth.forgot_password': 'Mot de passe oublié ?',
  'auth.dont_have_account': "Vous n'avez pas de compte ?",
  'auth.sign_in': 'Se connecter',
  'nav.economy_culture': 'Économie & Culture',
  'nav.explore_connect': 'Explorer & Connecter',
  'nav.people_creators': 'Personnes & Créateurs',
  'nav.view_all_results': 'Voir Tous les Résultats →',
};

const ht: Record<TranslationKey, string> = {
  'nav.home': 'Akèy',
  'nav.explore': 'Eksplore',
  'nav.reels': 'Reels',
  'nav.communities': 'Kominote',
  'nav.messages': 'Mesaj',
  'nav.notifications': 'Notifikasyon',
  'nav.events': 'Evènman',
  'nav.marketplace': 'Mache',
  'nav.saved': 'Sere',
  'nav.settings': 'Paramèt',
  'nav.creator_studio': 'Estidyo Kreyatè',
  'nav.business_studio': 'Estidyo Biznis',
  'nav.payments': 'Peman',
  'nav.profile': 'Pwofil',
  'nav.reels_shorts': 'Reels ak Kout',
  'nav.sounds': 'Son Karayib',
  'nav.live_streams': 'Difizyon an Dirèk',
  'nav.podcasts': 'Rezo Podkas',
  'nav.cultural_events': 'Evènman Kiltirèl',
  'nav.pages_stores': 'Paj ak Boutik',
  'nav.financial_center': 'Sant Finansye',
  'nav.map': 'Kat Karayib la',
  'nav.create_hub': 'Kreye Sant',
  'nav.sign_in': 'Konekte',
  'composer.placeholder': 'Kisa k ap pase ?',
  'composer.photo': 'Foto',
  'composer.video': 'Videyo',
  'composer.live': 'An dirèk',
  'composer.poll': 'Sondaj',
  'composer.post': 'Pibliye',
  'feed.for_you': 'Pou ou',
  'feed.following': 'Ap swiv',
  'feed.friends': 'Zanmi',
  'feed.caribbean': 'Karayib',
  'feed.local': 'Lokal',
  'feed.communities': 'Kominote',
  'feed.latest': 'Dènye',
  'feed.empty': 'Pa gen anyen isit. Swiv kreyatè epi rantre nan kominote.',
  'feed.loading': 'Ap chaje fil ou a…',
  'feed.error': 'Yon erè pase lè fil la ap chaje.',
  'action.like': 'Renmen',
  'action.comment': 'Kòmante',
  'action.share': 'Pataje',
  'action.save': 'Sere',
  'action.follow': 'Swiv',
  'action.following': 'Ap swiv',
  'search.placeholder': 'Chèche nan Karayib la…',
  'search.ask_caribbean': 'Mande Karayib la',
  'wallet.balance': 'Balans',
  'wallet.top_up': 'Rechaje',
  'wallet.send': 'Voye',
  'wallet.payouts': 'Peman',
  'community.join': 'Rantre',
  'community.leave': 'Soti',
  'community.members': 'Manm',
  'community.rules': 'Règ',
  'messages.empty': 'Pa gen konvèsasyon.',
  'messages.placeholder': 'Ekri yon mesaj…',
  'messages.send': 'Voye',
  'notifications.empty': 'Ou a jou.',
  'post.translate': 'Tradwi an {lang}',
  'post.show_original': 'Montre orijinal la',
  'post.translating': 'Ap tradwi…',
  'post.translated_from': 'Tradwi soti nan {lang}',
  'post.translation_unavailable': 'Tradiksyon an pa disponib pou kounye a.',
  'post.report': 'Siyale Kontni',
  'post.repost': 'Repibliye',
  'post.tip_creator': 'Bay Kreyatè a Ti Kouròn',
  'settings.language': 'Lang',
  'settings.language_title': 'Lang ak Rejyon',
  'settings.language_description': 'Chwazi lang ou pi pito pou platfòm TUKUBI a.',
  'settings.language_updated': 'Preferans lang sovgade.',
  'settings.save_changes': 'Sovgade Chanjman yo',
  'settings.account': 'Kont',
  'settings.privacy': 'Konfidansyalite',
  'settings.notifications': 'Notifikasyon',
  'onboarding.choose_language': 'Chwazi lang ou',
  'onboarding.language_subtitle': 'Chwazi lang ou pi pito. Ou ka chanje sa nenpòt ki lè nan Paramèt.',
  'onboarding.welcome': 'Byenvini sou TUKUBI',
  'onboarding.identity_title': 'Konfigirasyon Idantite',
  'onboarding.identity_subtitle': 'Pou pèsonalize fil kiltirèl ou epi konekte ak dyaspora ou, chwazi rasin Karayib ou.',
  'onboarding.search_roots': 'Chèche nan tout plis pase 30 zile ak teritwa…',
  'onboarding.diaspora_question': 'Èske w ap viv deyò teritwa natal ou (Dyaspora) ?',
  'onboarding.continue': 'Kontinye',
  'marketplace.title': 'Mache',
  'marketplace.search': 'Chèche nan mache a…',
  'marketplace.buy_now': 'Achte Kounye a',
  'marketplace.add_to_cart': 'Mete nan Panyen',
  'marketplace.out_of_stock': 'Fini',
  'a11y.open_menu': 'Louvri meni',
  'a11y.close': 'Fèmen',
  'a11y.search': 'Chèche',
  'time.just_now': 'Kounye a',
  'time.minutes_ago': 'Sa gen {count}m',
  'time.hours_ago': 'Sa gen {count}h',
  'time.days_ago': 'Sa gen {count}j',
  'common.loading': 'Ap chaje…',
  'common.error': 'Yon erè pase.',
  'common.retry': 'Eseye ankò',
  'common.cancel': 'Anile',
  'common.save': 'Sere',
  'common.delete': 'Efase',
  'common.see_more': 'Wè plis',
  'common.offline': 'Ou dekonekte. Kontni an kachèt ap afiche.',
  'common.private': 'Prive',
  'gateway.tagline': 'Yon Karayib. Yon Kominote. Yon Sèl Kay Dijital.',
  'gateway.hero_title_1': 'Karayib Ou.',
  'gateway.hero_connected': 'Konekte.',
  'gateway.hero_empowered': 'Otonòm.',
  'gateway.hero_subtitle': 'Karayib la ak dyaspora mondyal li reyini nan yon sèl platfòm pou konekte ak fanmi ak kilti, kreye kontni, dekouvri komès, epi pwospere.',
  'gateway.join_tukubi': 'Antre nan Tukubi',
  'gateway.create_account': 'Kreye yon Kont',
  'gateway.spotlight': 'Limyè sou Karayib la',
  'auth.welcome_back': 'Byenvini ankò',
  'auth.signin_subtitle': 'Konekte sou TUKUBI — Karayib la Konekte.',
  'auth.email_label': 'Imèl oswa telefòn',
  'auth.password_label': 'Modpas',
  'auth.remember_me': 'Sonje mwen',
  'auth.forgot_password': 'Bliye modpas?',
  'auth.dont_have_account': 'Ou pa gen yon kont?',
  'auth.sign_in': 'Konekte',
  'nav.economy_culture': 'Ekonomi & Kilti',
  'nav.explore_connect': 'Eksplore & Konekte',
  'nav.people_creators': 'Moun & Kreyatè',
  'nav.view_all_results': 'Wè Tout Rezilta Yo →',
};

const nl: Record<TranslationKey, string> = {
  'nav.home': 'Home',
  'nav.explore': 'Ontdekken',
  'nav.reels': 'Reels',
  'nav.communities': 'Communities',
  'nav.messages': 'Berichten',
  'nav.notifications': 'Meldingen',
  'nav.events': 'Evenementen',
  'nav.marketplace': 'Marktplaats',
  'nav.saved': 'Opgeslagen',
  'nav.settings': 'Instellingen',
  'nav.creator_studio': 'Creator Studio',
  'nav.business_studio': 'Business Studio',
  'nav.payments': 'Betalingen',
  'nav.profile': 'Profiel',
  'nav.reels_shorts': 'Reels & Korte video’s',
  'nav.sounds': 'Caribische Geluiden',
  'nav.live_streams': 'Livestreams',
  'nav.podcasts': 'Podcastnetwerk',
  'nav.cultural_events': 'Culturele Evenementen',
  'nav.pages_stores': 'Pagina’s & Winkels',
  'nav.financial_center': 'Financieel Centrum',
  'nav.map': 'Caribische Kaart',
  'nav.create_hub': 'Maak Hub',
  'nav.sign_in': 'Inloggen',
  'composer.placeholder': 'Wat is er aan de hand?',
  'composer.photo': 'Foto',
  'composer.video': 'Video',
  'composer.live': 'Live',
  'composer.poll': 'Poll',
  'composer.post': 'Plaatsen',
  'feed.for_you': 'Voor jou',
  'feed.following': 'Volgend',
  'feed.friends': 'Vrienden',
  'feed.caribbean': 'Caribisch',
  'feed.local': 'Lokaal',
  'feed.communities': 'Communities',
  'feed.latest': 'Nieuwste',
  'feed.empty': 'Nog niets hier. Volg makers en word lid van communities.',
  'feed.loading': 'Feed laden…',
  'feed.error': 'Er ging iets mis bij het laden van de feed.',
  'action.like': 'Vind ik leuk',
  'action.comment': 'Reageren',
  'action.share': 'Delen',
  'action.save': 'Opslaan',
  'action.follow': 'Volgen',
  'action.following': 'Volgend',
  'search.placeholder': 'Zoek in het Caribisch gebied…',
  'search.ask_caribbean': 'Vraag het Cariben',
  'wallet.balance': 'Saldo',
  'wallet.top_up': 'Opwaarderen',
  'wallet.send': 'Versturen',
  'wallet.payouts': 'Uitbetalingen',
  'community.join': 'Lid worden',
  'community.leave': 'Verlaten',
  'community.members': 'Leden',
  'community.rules': 'Regels',
  'messages.empty': 'Nog geen gesprekken.',
  'messages.placeholder': 'Schrijf een bericht…',
  'messages.send': 'Versturen',
  'notifications.empty': 'Je bent helemaal bij.',
  'post.translate': 'Vertalen naar {lang}',
  'post.show_original': 'Origineel tonen',
  'post.translating': 'Vertalen…',
  'post.translated_from': 'Vertaald uit het {lang}',
  'post.translation_unavailable': 'Vertaling tijdelijk niet beschikbaar.',
  'post.report': 'Inhoud Rapporteren',
  'post.repost': 'Opnieuw plaatsen',
  'post.tip_creator': 'Maker Fooi Geven',
  'settings.language': 'Taal',
  'settings.language_title': 'Taal & Regio',
  'settings.language_description': 'Selecteer uw voorkeurstaal voor het TUKUBI-platform.',
  'settings.language_updated': 'Taalvoorkeur opgeslagen.',
  'settings.save_changes': 'Wijzigingen Opslaan',
  'settings.account': 'Account',
  'settings.privacy': 'Privacy',
  'settings.notifications': 'Meldingen',
  'onboarding.choose_language': 'Kies uw taal',
  'onboarding.language_subtitle': 'Selecteer uw voorkeurstaal. U kunt dit op elk moment wijzigen via Instellingen.',
  'onboarding.welcome': 'Welkom bij TUKUBI',
  'onboarding.identity_title': 'Identiteitsconfiguratie',
  'onboarding.identity_subtitle': 'Selecteer uw Caribische wortels om culturele feeds te personaliseren en contact te maken met uw diaspora.',
  'onboarding.search_roots': 'Zoek in meer dan 30 eilanden en gebieden…',
  'onboarding.diaspora_question': 'Woont u buiten uw thuisgebied (Diaspora)?',
  'onboarding.continue': 'Doorgaan',
  'marketplace.title': 'Marktplaats',
  'marketplace.search': 'Zoek in marktplaats…',
  'marketplace.buy_now': 'Nu Kopen',
  'marketplace.add_to_cart': 'In Winkelwagen',
  'marketplace.out_of_stock': 'Niet op voorraad',
  'a11y.open_menu': 'Menu openen',
  'a11y.close': 'Sluiten',
  'a11y.search': 'Zoeken',
  'time.just_now': 'Zojuist',
  'time.minutes_ago': '{count}m geleden',
  'time.hours_ago': '{count}u geleden',
  'time.days_ago': '{count}d geleden',
  'common.loading': 'Laden…',
  'common.error': 'Er ging iets mis.',
  'common.retry': 'Opnieuw proberen',
  'common.cancel': 'Annuleren',
  'common.save': 'Opslaan',
  'common.delete': 'Verwijderen',
  'common.see_more': 'Meer zien',
  'common.offline': 'Je bent offline. Gebufferde inhoud wordt getoond.',
  'common.private': 'Privé',
  'gateway.tagline': 'Eén Caraïben. Eén Gemeenschap. Eén Digitaal Thuis.',
  'gateway.hero_title_1': 'Jouw Caraïben.',
  'gateway.hero_connected': 'Verbonden.',
  'gateway.hero_empowered': 'Versterkt.',
  'gateway.hero_subtitle': 'Het Caribisch gebied en zijn wereldwijde diaspora verenigd op één platform om verbinding te maken met familie en cultuur, content te creëren, handel te ontdekken en te floreren.',
  'gateway.join_tukubi': 'Word lid van Tukubi',
  'gateway.create_account': 'Account Aanmaken',
  'gateway.spotlight': 'Caribische Spotlight',
  'auth.welcome_back': 'Welkom terug',
  'auth.signin_subtitle': 'Log in op TUKUBI — Het Caribisch Gebied Verbonden.',
  'auth.email_label': 'E-mail of telefoon',
  'auth.password_label': 'Wachtwoord',
  'auth.remember_me': 'Onthoud mij',
  'auth.forgot_password': 'Wachtwoord vergeten?',
  'auth.dont_have_account': 'Heb je nog geen account?',
  'auth.sign_in': 'Inloggen',
  'nav.economy_culture': 'Economie & Cultuur',
  'nav.explore_connect': 'Ontdekken & Verbinden',
  'nav.people_creators': 'Mensen & Makers',
  'nav.view_all_results': 'Bekijk Alle Resultaten →',
};

const pap: Record<TranslationKey, string> = {
  'nav.home': 'Kas',
  'nav.explore': 'Buska',
  'nav.reels': 'Reels',
  'nav.communities': 'Komunidat',
  'nav.messages': 'Mensah',
  'nav.notifications': 'Notifikashon',
  'nav.events': 'Eventunan',
  'nav.marketplace': 'Merka',
  'nav.saved': 'Warda',
  'nav.settings': 'Konfigurashon',
  'nav.creator_studio': 'Studio di Kreador',
  'nav.business_studio': 'Studio di Negoshi',
  'nav.payments': 'Pagonan',
  'nav.profile': 'Perfil',
  'nav.reels_shorts': 'Reels & Kortiko',
  'nav.sounds': 'Sonidonan di Karibe',
  'nav.live_streams': 'Transmití en Vivo',
  'nav.podcasts': 'Netwèrk di Podcast',
  'nav.cultural_events': 'Eventunan Kultural',
  'nav.pages_stores': 'Páginanan & Tiendanan',
  'nav.financial_center': 'Sentro Finansiero',
  'nav.map': 'Mapa di Karibe',
  'nav.create_hub': 'Krea Sentro',
  'nav.sign_in': 'Drenta',
  'composer.placeholder': 'Ki ta pasando?',
  'composer.photo': 'Fotografi',
  'composer.video': 'Video',
  'composer.live': 'En vivo',
  'composer.poll': 'Enkuesta',
  'composer.post': 'Publiká',
  'feed.for_you': 'Pa bo',
  'feed.following': 'Siguiendo',
  'feed.friends': 'Amigonan',
  'feed.caribbean': 'Karibe',
  'feed.local': 'Lokal',
  'feed.communities': 'Komunidat',
  'feed.latest': 'Mas nobo',
  'feed.empty': 'Nada aki ainda. Siguí kreadónan i drentá komunidatnan.',
  'feed.loading': 'Kargando bo feed…',
  'feed.error': 'Algo a bai mal kargando e feed.',
  'action.like': 'Ta gusta',
  'action.comment': 'Komentá',
  'action.share': 'Compartí',
  'action.save': 'Warda',
  'action.follow': 'Siguí',
  'action.following': 'Siguiendo',
  'search.placeholder': 'Buska na Karibe…',
  'search.ask_caribbean': 'Preguntá Karibe',
  'wallet.balance': 'Balans',
  'wallet.top_up': 'Karga',
  'wallet.send': 'Manda',
  'wallet.payouts': 'Pagonan',
  'community.join': 'Drentá',
  'community.leave': 'Salí',
  'community.members': 'Miembronan',
  'community.rules': 'Reglanan',
  'messages.empty': 'No tin konversashon ainda.',
  'messages.placeholder': 'Skirbi un mensah…',
  'messages.send': 'Manda',
  'notifications.empty': 'Bo ta al dia.',
  'post.translate': 'Tradusí na {lang}',
  'post.show_original': 'Mostra original',
  'post.translating': 'Tradusiendo…',
  'post.translated_from': 'Tradusí for di {lang}',
  'post.translation_unavailable': 'Traduccion no ta disponibel temporalmente.',
  'post.report': 'Rapòrt Kontenido',
  'post.repost': 'Publiká di nobo',
  'post.tip_creator': 'Duna Propina',
  'settings.language': 'Idioma',
  'settings.language_title': 'Idioma & Region',
  'settings.language_description': 'Selekshoná bo idioma preferí pa e plataforma TUKUBI.',
  'settings.language_updated': 'Preferencia di idioma a keda wardá.',
  'settings.save_changes': 'Warda Kambionan',
  'settings.account': 'Kuenta',
  'settings.privacy': 'Privasidat',
  'settings.notifications': 'Notifikashon',
  'onboarding.choose_language': 'Skohe bo idioma',
  'onboarding.language_subtitle': 'Selekshoná bo idioma preferí. Bo por kambia esaki kualke momento den Konfigurashon.',
  'onboarding.welcome': 'Bon bini na TUKUBI',
  'onboarding.identity_title': 'Konfigurashon di Identidat',
  'onboarding.identity_subtitle': 'Pa personalisá bo feed kultural i konektá ku bo diasporá, skohe bo raisnan Karibe.',
  'onboarding.search_roots': 'Buska den mas ku 30 isla i teritorio…',
  'onboarding.diaspora_question': 'Bo ta biba pafó di bo teritorio natal (Diaspora)?',
  'onboarding.continue': 'Kontinuá',
  'marketplace.title': 'Merka',
  'marketplace.search': 'Buska den merka…',
  'marketplace.buy_now': 'Kumpra Awor',
  'marketplace.add_to_cart': 'Pone den Kiri',
  'marketplace.out_of_stock': 'A kaba',
  'a11y.open_menu': 'Habri menu',
  'a11y.close': 'Sera',
  'a11y.search': 'Buska',
  'time.just_now': 'Djis awor',
  'time.minutes_ago': '{count}m pasá',
  'time.hours_ago': '{count}o pasá',
  'time.days_ago': '{count}d pasá',
  'common.loading': 'Kargando…',
  'common.error': 'Algo a bai mal.',
  'common.retry': 'Inténta otron bia',
  'common.cancel': 'Kanselá',
  'common.save': 'Warda',
  'common.delete': 'Kita',
  'common.see_more': 'Wak mas',
  'common.offline': 'Bo ta offline. Mostrando kontenido kashá.',
  'common.private': 'Privá',
  'gateway.tagline': 'Un Karibe. Un Komunidat. Un Kas Digital.',
  'gateway.hero_title_1': 'Bo Karibe.',
  'gateway.hero_connected': 'Konekta.',
  'gateway.hero_empowered': 'Empoderá.',
  'gateway.hero_subtitle': 'Karibe i su diaspora global uni riba un plataforma pa konektá ku famia i kultura, krea kontenido, deskubrí komèrsio i prosperá.',
  'gateway.join_tukubi': 'Drenta Tukubi',
  'gateway.create_account': 'Krea un Kuenta',
  'gateway.spotlight': 'Lus riba Karibe',
  'auth.welcome_back': 'Bon biní bèk',
  'auth.signin_subtitle': 'Inisiá seshon na TUKUBI — E Karibe Konekta.',
  'auth.email_label': 'Email òf telefòn',
  'auth.password_label': 'Kontraseña',
  'auth.remember_me': 'Kòrda riba mi',
  'auth.forgot_password': 'A lubidá kontraseña?',
  'auth.dont_have_account': 'Bo no tin un kuenta?',
  'auth.sign_in': 'Inisiá seshon',
  'nav.economy_culture': 'Ekonomia & Kultura',
  'nav.explore_connect': 'Eksplorá & Konektá',
  'nav.people_creators': 'Hende & Kreador',
  'nav.view_all_results': 'Mira Tur Resultado →',
};

export const dictionaries: Record<Locale, Record<TranslationKey, string>> = { en, es, fr, ht, nl, pap };

export function isLocale(value: string): value is Locale {
  return (LOCALES as readonly string[]).includes(value);
}

export function t(locale: Locale, key: TranslationKey, params?: Record<string, string | number>): string {
  let template = dictionaries[locale]?.[key] ?? dictionaries[DEFAULT_LOCALE]?.[key] ?? key;
  if (params) {
    for (const [pKey, pVal] of Object.entries(params)) {
      template = template.replace(new RegExp('\\{' + pKey + '\\}', 'g'), String(pVal));
    }
  }
  return template;
}

export function tPlural(
  locale: Locale,
  key: TranslationKey,
  count: number,
  params?: Record<string, string | number>
): string {
  return t(locale, key, { count, ...params });
}

export function formatDate(
  date: Date | string | number,
  locale: Locale,
  options?: Intl.DateTimeFormatOptions
): string {
  const d = typeof date === 'object' ? date : new Date(date);
  const localeTag = locale === 'pap' ? 'nl-CW' : locale === 'ht' ? 'fr-HT' : locale;
  try {
    return new Intl.DateTimeFormat(localeTag, options || { dateStyle: 'medium' }).format(d);
  } catch {
    return d.toLocaleDateString();
  }
}

export function formatRelativeTime(date: Date | string | number, locale: Locale): string {
  const d = typeof date === 'object' ? date.getTime() : new Date(date).getTime();
  const diffMs = Date.now() - d;
  const diffSec = Math.floor(diffMs / 1000);
  if (diffSec < 60) return t(locale, 'time.just_now');
  const diffMin = Math.floor(diffSec / 60);
  if (diffMin < 60) return t(locale, 'time.minutes_ago', { count: diffMin });
  const diffHours = Math.floor(diffMin / 60);
  if (diffHours < 24) return t(locale, 'time.hours_ago', { count: diffHours });
  const diffDays = Math.floor(diffHours / 24);
  return t(locale, 'time.days_ago', { count: diffDays });
}

export function formatNumber(value: number, locale: Locale, options?: Intl.NumberFormatOptions): string {
  const localeTag = locale === 'pap' ? 'nl-CW' : locale === 'ht' ? 'fr-HT' : locale;
  try {
    return new Intl.NumberFormat(localeTag, options).format(value);
  } catch {
    return String(value);
  }
}

export function formatCurrency(amount: number, currency: string, locale: Locale): string {
  const localeTag = locale === 'pap' ? 'nl-CW' : locale === 'ht' ? 'fr-HT' : locale;
  try {
    return new Intl.NumberFormat(localeTag, { style: 'currency', currency }).format(amount);
  } catch {
    return currency.toUpperCase() + ' ' + amount.toFixed(2);
  }
}

export function missingKeys(locale: Locale): TranslationKey[] {
  const reference = Object.keys(dictionaries[DEFAULT_LOCALE]) as TranslationKey[];
  return reference.filter((key) => dictionaries[locale]?.[key] === undefined);
}

export * from './service';
export * from './react';
