/**
 * Canonical Caribbean Geospatial Data & Coordinates
 *
 * Single Source of Truth for the Tukubi Geographic Discovery Map.
 * Provides accurate relative coordinates (0-1000 x 0-750 canvas space),
 * regional classifications, cultural descriptions, and deep-link mappings.
 */

export interface CaribbeanGeoEntity {
  iso: string;
  name: string;
  shortName: string;
  capital: string;
  flag: string;
  region:
    | 'Greater Antilles'
    | 'Lesser Antilles (Leeward)'
    | 'Lesser Antilles (Windward)'
    | 'Southern Caribbean & ABC'
    | 'Guianas & Mainland Coast'
    | 'Diaspora Hub';
  x: number;
  y: number;
  r: number;
  sovereign: boolean;
  trendingTag: string;
  creatorsCount: string;
  businessesCount: string;
  eventsCount: string;
  activeLive: number;
  summary: string;
  diasporaLinks?: string[];
}

export const CARIBBEAN_GEO_ENTITIES: CaribbeanGeoEntity[] = [
  // ── Greater Antilles & Lucayan Archipelago ──
  {
    iso: 'BHS',
    name: 'The Bahamas',
    shortName: 'Bahamas',
    capital: 'Nassau',
    flag: '🇧🇸',
    region: 'Greater Antilles',
    x: 270,
    y: 190,
    r: 7,
    sovereign: true,
    trendingTag: '#JunkanooVibes',
    creatorsCount: '4.8K',
    businessesCount: '740',
    eventsCount: '16 Events',
    activeLive: 4,
    summary: 'Junkanoo spectacle, crystal turquoise archipelagos, maritime commerce, and vibrant conch culture.',
    diasporaLinks: ['MIA', 'ATL', 'NYC'],
  },
  {
    iso: 'CUB',
    name: 'Cuba',
    shortName: 'Cuba',
    capital: 'Havana',
    flag: '🇨🇺',
    region: 'Greater Antilles',
    x: 250,
    y: 280,
    r: 11,
    sovereign: true,
    trendingTag: '#SonCubano',
    creatorsCount: '19.2K',
    businessesCount: '1,800',
    eventsCount: '28 Events',
    activeLive: 9,
    summary: 'Son, Rumba, Afro-Cuban jazz, historic colonial architecture, classic automotive art, and literary legacy.',
    diasporaLinks: ['MIA', 'NYC', 'MAD'],
  },
  {
    iso: 'CYM',
    name: 'Cayman Islands',
    shortName: 'Cayman',
    capital: 'George Town',
    flag: '🇰🇾',
    region: 'Greater Antilles',
    x: 195,
    y: 340,
    r: 5,
    sovereign: false,
    trendingTag: '#CaymanCarnival',
    creatorsCount: '2.1K',
    businessesCount: '620',
    eventsCount: '12 Events',
    activeLive: 3,
    summary: 'Global financial hub, Batabano carnival, stingray sandbars, and culinary excellence in the Western Caribbean.',
    diasporaLinks: ['MIA', 'LON', 'TOR'],
  },
  {
    iso: 'JAM',
    name: 'Jamaica',
    shortName: 'Jamaica',
    capital: 'Kingston',
    flag: '🇯🇲',
    region: 'Greater Antilles',
    x: 285,
    y: 375,
    r: 9.5,
    sovereign: true,
    trendingTag: '#KingstonVibes',
    creatorsCount: '24.5K',
    businessesCount: '3,800',
    eventsCount: '64 Fetes',
    activeLive: 19,
    summary: 'Heart of Reggae, Dancehall, Sound System culture, Blue Mountain coffee, track & field supremacy, and Jerk cuisine.',
    diasporaLinks: ['NYC', 'MIA', 'TOR', 'LON'],
  },
  {
    iso: 'HTI',
    name: 'Haiti',
    shortName: 'Haiti',
    capital: 'Port-au-Prince',
    flag: '🇭🇹',
    region: 'Greater Antilles',
    x: 375,
    y: 345,
    r: 9,
    sovereign: true,
    trendingTag: '#AyitiArt',
    creatorsCount: '14.8K',
    businessesCount: '1,450',
    eventsCount: '24 Events',
    activeLive: 8,
    summary: 'Pioneering republic, vibrant metal and canvas fine art, Kompa rhythms, artisanal coffee, and rich diaspora history.',
    diasporaLinks: ['MIA', 'NYC', 'MTL', 'PAR'],
  },
  {
    iso: 'DOM',
    name: 'Dominican Republic',
    shortName: 'Dominican Rep.',
    capital: 'Santo Domingo',
    flag: '🇩🇴',
    region: 'Greater Antilles',
    x: 440,
    y: 345,
    r: 10,
    sovereign: true,
    trendingTag: '#RDTechSummit',
    creatorsCount: '28.1K',
    businessesCount: '4,200',
    eventsCount: '52 Events',
    activeLive: 22,
    summary: 'Bachata, Merengue, artisanal organic cacao, Caribbean tech innovation, historic Zona Colonial, and baseball pride.',
    diasporaLinks: ['NYC', 'MIA', 'BOS', 'MAD'],
  },
  {
    iso: 'TCA',
    name: 'Turks & Caicos Islands',
    shortName: 'Turks & Caicos',
    capital: 'Cockburn Town',
    flag: '🇹🇨',
    region: 'Greater Antilles',
    x: 420,
    y: 260,
    r: 5.5,
    sovereign: false,
    trendingTag: '#ProvoVibes',
    creatorsCount: '2.4K',
    businessesCount: '410',
    eventsCount: '10 Events',
    activeLive: 2,
    summary: 'Rake and scrape music, Grace Bay turquoise reefs, luxury ecotourism, and vibrant conch festivals.',
    diasporaLinks: ['MIA', 'NYC', 'TOR'],
  },
  {
    iso: 'PRI',
    name: 'Puerto Rico',
    shortName: 'Puerto Rico',
    capital: 'San Juan',
    flag: '🇵🇷',
    region: 'Greater Antilles',
    x: 530,
    y: 360,
    r: 9,
    sovereign: false,
    trendingTag: '#SanJuanNights',
    creatorsCount: '26.4K',
    businessesCount: '3,900',
    eventsCount: '48 Events',
    activeLive: 17,
    summary: 'Boricua pride, Salsa and Reggaeton origins, Old San Juan cobblestone arts, culinary fusions, and diaspora bridges.',
    diasporaLinks: ['NYC', 'ORL', 'MIA', 'PHL'],
  },

  // ── Lesser Antilles (Leeward Islands) ──
  {
    iso: 'VIR',
    name: 'US Virgin Islands',
    shortName: 'USVI',
    capital: 'Charlotte Amalie',
    flag: '🇻🇮',
    region: 'Lesser Antilles (Leeward)',
    x: 580,
    y: 360,
    r: 5,
    sovereign: false,
    trendingTag: '#StThomasCarnival',
    creatorsCount: '3.1K',
    businessesCount: '520',
    eventsCount: '14 Events',
    activeLive: 4,
    summary: 'St. Thomas, St. John, and St. Croix heritage, quelbe music, Danish colonial architecture, and carnival pageantry.',
    diasporaLinks: ['ATL', 'MIA', 'NYC'],
  },
  {
    iso: 'VGB',
    name: 'British Virgin Islands',
    shortName: 'BVI',
    capital: 'Road Town',
    flag: '🇻🇬',
    region: 'Lesser Antilles (Leeward)',
    x: 600,
    y: 355,
    r: 4.5,
    sovereign: false,
    trendingTag: '#TortolaLife',
    creatorsCount: '1.8K',
    businessesCount: '490',
    eventsCount: '9 Events',
    activeLive: 2,
    summary: 'Sailing capital of the world, The Baths geological wonder, yachting regattas, and fungi music.',
    diasporaLinks: ['LON', 'MIA', 'NYC'],
  },
  {
    iso: 'AIA',
    name: 'Anguilla',
    shortName: 'Anguilla',
    capital: 'The Valley',
    flag: '🇦🇮',
    region: 'Lesser Antilles (Leeward)',
    x: 625,
    y: 350,
    r: 4.5,
    sovereign: false,
    trendingTag: '#AnguillaSummerFest',
    creatorsCount: '1.2K',
    businessesCount: '280',
    eventsCount: '8 Events',
    activeLive: 2,
    summary: 'Tranquil pristine beaches, boat racing national sport, culinary capital status, and lively summer festivals.',
    diasporaLinks: ['LON', 'NYC', 'MIA'],
  },
  {
    iso: 'SXM',
    name: 'Sint Maarten / Saint-Martin',
    shortName: 'Sint Maarten',
    capital: 'Philipsburg',
    flag: '🇸🇽',
    region: 'Lesser Antilles (Leeward)',
    x: 632,
    y: 365,
    r: 5,
    sovereign: false,
    trendingTag: '#SXMCarnival',
    creatorsCount: '3.8K',
    businessesCount: '690',
    eventsCount: '18 Events',
    activeLive: 5,
    summary: 'The Friendly Island, dual Dutch-French heritage, duty-free shopping, Maho beach, and vibrant Grand Carnival.',
    diasporaLinks: ['AMS', 'PAR', 'MIA'],
  },
  {
    iso: 'KNA',
    name: 'Saint Kitts & Nevis',
    shortName: 'St. Kitts & Nevis',
    capital: 'Basseterre',
    flag: '🇰🇳',
    region: 'Lesser Antilles (Leeward)',
    x: 630,
    y: 388,
    r: 5,
    sovereign: true,
    trendingTag: '#SugarMas',
    creatorsCount: '2.5K',
    businessesCount: '380',
    eventsCount: '11 Events',
    activeLive: 3,
    summary: 'Sugar Mas carnival, Brimstone Hill fortress UNESCO site, Caribbean music festival, and rainforest peaks.',
    diasporaLinks: ['LON', 'NYC', 'TOR'],
  },
  {
    iso: 'ATG',
    name: 'Antigua & Barbuda',
    shortName: 'Antigua',
    capital: "St. John's",
    flag: '🇦🇬',
    region: 'Lesser Antilles (Leeward)',
    x: 662,
    y: 385,
    r: 6,
    sovereign: true,
    trendingTag: '#AntiguaSailingWeek',
    creatorsCount: '4.2K',
    businessesCount: '620',
    eventsCount: '19 Events',
    activeLive: 5,
    summary: '365 white sand beaches, Antigua Sailing Week, Nelson’s Dockyard maritime history, and sweet Benna music.',
    diasporaLinks: ['LON', 'NYC', 'TOR'],
  },
  {
    iso: 'MSR',
    name: 'Montserrat',
    shortName: 'Montserrat',
    capital: 'Brades (de facto)',
    flag: '🇲🇸',
    region: 'Lesser Antilles (Leeward)',
    x: 638,
    y: 412,
    r: 4.5,
    sovereign: false,
    trendingTag: '#EmeraldIsle',
    creatorsCount: '950',
    businessesCount: '140',
    eventsCount: '6 Events',
    activeLive: 1,
    summary: 'The Emerald Isle of the Caribbean, rich Irish-African cultural blend, Soufrière Hills volcano, and Calypso kings.',
    diasporaLinks: ['LON', 'BHM', 'TOR'],
  },
  {
    iso: 'GLP',
    name: 'Guadeloupe',
    shortName: 'Guadeloupe',
    capital: 'Basse-Terre',
    flag: '🇬🇵',
    region: 'Lesser Antilles (Leeward)',
    x: 668,
    y: 428,
    r: 7,
    sovereign: false,
    trendingTag: '#GwokaVibes',
    creatorsCount: '7.8K',
    businessesCount: '1,100',
    eventsCount: '22 Events',
    activeLive: 6,
    summary: 'Butterfly archipelago, Gwo Ka drum heritage, Creole gastronomy, La Soufrière volcano hikes, and Zouk music.',
    diasporaLinks: ['PAR', 'MTL', 'MAR'],
  },
  {
    iso: 'DMA',
    name: 'Dominica',
    shortName: 'Dominica',
    capital: 'Roseau',
    flag: '🇩🇲',
    region: 'Lesser Antilles (Leeward)',
    x: 660,
    y: 462,
    r: 5.5,
    sovereign: true,
    trendingTag: '#NatureIsle',
    creatorsCount: '2.9K',
    businessesCount: '340',
    eventsCount: '13 Events',
    activeLive: 3,
    summary: 'The Nature Island, Boiling Lake geothermal wonder, World Creole Music Festival, and Kalinago indigenous territory.',
    diasporaLinks: ['LON', 'NYC', 'TOR'],
  },

  // ── Lesser Antilles (Windward Islands) ──
  {
    iso: 'MTQ',
    name: 'Martinique',
    shortName: 'Martinique',
    capital: 'Fort-de-France',
    flag: '🇲🇶',
    region: 'Lesser Antilles (Windward)',
    x: 668,
    y: 492,
    r: 7,
    sovereign: false,
    trendingTag: '#MartiniqueZouk',
    creatorsCount: '8.4K',
    businessesCount: '1,250',
    eventsCount: '26 Events',
    activeLive: 7,
    summary: 'Isle of Flowers, birthplace of Zouk, Tour des Yoles round-island boat race, rum distilleries, and Aimé Césaire poetry.',
    diasporaLinks: ['PAR', 'MTL', 'LYO'],
  },
  {
    iso: 'LCA',
    name: 'Saint Lucia',
    shortName: 'Saint Lucia',
    capital: 'Castries',
    flag: '🇱🇨',
    region: 'Lesser Antilles (Windward)',
    x: 665,
    y: 525,
    r: 6.5,
    sovereign: true,
    trendingTag: '#LucianCarnival',
    creatorsCount: '6.1K',
    businessesCount: '840',
    eventsCount: '23 Events',
    activeLive: 6,
    summary: 'Majestic volcanic Gros and Petit Pitons, Saint Lucia Jazz Festival, sulphur springs, and Dennery Segment soca.',
    diasporaLinks: ['LON', 'NYC', 'TOR'],
  },
  {
    iso: 'BRB',
    name: 'Barbados',
    shortName: 'Barbados',
    capital: 'Bridgetown',
    flag: '🇧🇧',
    region: 'Lesser Antilles (Windward)',
    x: 722,
    y: 535,
    r: 7.5,
    sovereign: true,
    trendingTag: '#CropOver2026',
    creatorsCount: '9.8K',
    businessesCount: '1,420',
    eventsCount: '34 Events',
    activeLive: 11,
    summary: 'Culinary capital, historic Mount Gay aged rum heritage, Crop Over Grand Kadooment, and Caribbean fintech leadership.',
    diasporaLinks: ['NYC', 'LON', 'TOR', 'MIA'],
  },
  {
    iso: 'VCT',
    name: 'Saint Vincent & the Grenadines',
    shortName: 'St. Vincent',
    capital: 'Kingstown',
    flag: '🇻🇨',
    region: 'Lesser Antilles (Windward)',
    x: 652,
    y: 555,
    r: 6,
    sovereign: true,
    trendingTag: '#VincyMas',
    creatorsCount: '3.4K',
    businessesCount: '460',
    eventsCount: '15 Events',
    activeLive: 4,
    summary: 'Vincy Mas festival, 32 idyllic Grenadines isles including Bequia & Mustique, La Soufrière trails, and artisanal yachting.',
    diasporaLinks: ['NYC', 'LON', 'TOR'],
  },
  {
    iso: 'GRD',
    name: 'Grenada',
    shortName: 'Grenada',
    capital: "St. George's",
    flag: '🇬🇩',
    region: 'Lesser Antilles (Windward)',
    x: 648,
    y: 588,
    r: 6,
    sovereign: true,
    trendingTag: '#Spicemas',
    creatorsCount: '4.9K',
    businessesCount: '580',
    eventsCount: '17 Events',
    activeLive: 5,
    summary: 'The Spice Isle of nutmeg and organic cocoa, Spicemas Jab Jab carnival ritual, Grand Anse beach, and underwater sculpture park.',
    diasporaLinks: ['NYC', 'LON', 'TOR'],
  },

  // ── Southern Caribbean & ABC Islands ──
  {
    iso: 'TTO',
    name: 'Trinidad & Tobago',
    shortName: 'Trinidad & Tobago',
    capital: 'Port of Spain',
    flag: '🇹🇹',
    region: 'Southern Caribbean & ABC',
    x: 672,
    y: 628,
    r: 9.5,
    sovereign: true,
    trendingTag: '#CarnivalTT',
    creatorsCount: '21.3K',
    businessesCount: '3,400',
    eventsCount: '78 Fetes',
    activeLive: 24,
    summary: 'Birthplace of Steelpan, Soca, Calypso, and the greatest carnival spectacle on earth; diverse culinary doubles and roti culture.',
    diasporaLinks: ['NYC', 'MIA', 'TOR', 'LON', 'HOU'],
  },
  {
    iso: 'ABW',
    name: 'Aruba',
    shortName: 'Aruba',
    capital: 'Oranjestad',
    flag: '🇦🇼',
    region: 'Southern Caribbean & ABC',
    x: 420,
    y: 535,
    r: 6,
    sovereign: false,
    trendingTag: '#OneHappyIsland',
    creatorsCount: '5.2K',
    businessesCount: '810',
    eventsCount: '16 Events',
    activeLive: 5,
    summary: 'One Happy Island, divi-divi trees, desert cactus landscapes alongside turquoise seas, Papiamento language, and festive dande music.',
    diasporaLinks: ['AMS', 'MIA', 'NYC'],
  },
  {
    iso: 'CUW',
    name: 'Curaçao',
    shortName: 'Curaçao',
    capital: 'Willemstad',
    flag: '🇨🇼',
    region: 'Southern Caribbean & ABC',
    x: 460,
    y: 545,
    r: 6.5,
    sovereign: false,
    trendingTag: '#WillemstadArt',
    creatorsCount: '6.4K',
    businessesCount: '920',
    eventsCount: '20 Events',
    activeLive: 6,
    summary: 'UNESCO Willemstad Handelskade waterfront, Curaçao North Sea Jazz festival, blue liqueur heritage, and rich Afro-Caribbean folklore.',
    diasporaLinks: ['AMS', 'MIA', 'NYC'],
  },
  {
    iso: 'BES',
    name: 'Bonaire',
    shortName: 'Bonaire',
    capital: 'Kralendijk',
    flag: '🇧🇶',
    region: 'Southern Caribbean & ABC',
    x: 490,
    y: 545,
    r: 5,
    sovereign: false,
    trendingTag: '#DiversParadise',
    creatorsCount: '1.4K',
    businessesCount: '240',
    eventsCount: '7 Events',
    activeLive: 2,
    summary: 'Diver’s paradise marine sanctuary, pink flamingo salt flats, windsurfing world records at Lac Bay, and tranquil eco-living.',
    diasporaLinks: ['AMS', 'MIA'],
  },

  // ── Guianas & Mainland Caribbean Coast ──
  {
    iso: 'BLZ',
    name: 'Belize',
    shortName: 'Belize',
    capital: 'Belmopan',
    flag: '🇧🇿',
    region: 'Guianas & Mainland Coast',
    x: 80,
    y: 320,
    r: 7,
    sovereign: true,
    trendingTag: '#BelizeBarrierReef',
    creatorsCount: '3.6K',
    businessesCount: '480',
    eventsCount: '12 Events',
    activeLive: 3,
    summary: 'Garifuna drum music, Belize Great Blue Hole barrier reef, ancient Maya temples, and lush tropical jungle biodiversity.',
    diasporaLinks: ['LAX', 'CHI', 'MIA'],
  },
  {
    iso: 'PAN',
    name: 'Panama (Caribbean Coast)',
    shortName: 'Panama',
    capital: 'Panama City',
    flag: '🇵🇦',
    region: 'Guianas & Mainland Coast',
    x: 230,
    y: 590,
    r: 7,
    sovereign: true,
    trendingTag: '#BocasDelToro',
    creatorsCount: '8.9K',
    businessesCount: '1,500',
    eventsCount: '22 Events',
    activeLive: 7,
    summary: 'Bocas del Toro archipelago, Afro-Antillean heritage in Colón, Reggae en Español pioneers, and the Panama Canal trade gateway.',
    diasporaLinks: ['MIA', 'NYC', 'ATL'],
  },
  {
    iso: 'COL',
    name: 'Colombia (Caribbean Region)',
    shortName: 'Colombia Coast',
    capital: 'Cartagena / Barranquilla',
    flag: '🇨🇴',
    region: 'Guianas & Mainland Coast',
    x: 310,
    y: 560,
    r: 8,
    sovereign: true,
    trendingTag: '#CarnavalDeBarranquilla',
    creatorsCount: '17.4K',
    businessesCount: '2,600',
    eventsCount: '42 Events',
    activeLive: 14,
    summary: 'Barranquilla UNESCO Carnival, historic walled Cartagena, Cumbia rhythms, Palenque Afro-heritage, and coastal arts.',
    diasporaLinks: ['MIA', 'NYC', 'MAD'],
  },
  {
    iso: 'GUY',
    name: 'Guyana',
    shortName: 'Guyana',
    capital: 'Georgetown',
    flag: '🇬🇾',
    region: 'Guianas & Mainland Coast',
    x: 800,
    y: 660,
    r: 8,
    sovereign: true,
    trendingTag: '#GuyanaMash',
    creatorsCount: '5.8K',
    businessesCount: '920',
    eventsCount: '18 Events',
    activeLive: 6,
    summary: 'Land of Many Waters, Kaieteur single-drop falls, Mashramani celebration, rainforest conservation, and energy innovation.',
    diasporaLinks: ['NYC', 'TOR', 'LON', 'MIA'],
  },
  {
    iso: 'SUR',
    name: 'Suriname',
    shortName: 'Suriname',
    capital: 'Paramaribo',
    flag: '🇸🇷',
    region: 'Guianas & Mainland Coast',
    x: 860,
    y: 675,
    r: 7.5,
    sovereign: true,
    trendingTag: '#KasekoMusic',
    creatorsCount: '4.1K',
    businessesCount: '670',
    eventsCount: '14 Events',
    activeLive: 4,
    summary: 'Kaseko music, Paramaribo UNESCO wooden Dutch architecture, Maroon and Javanese heritage, and Amazonian ecotourism.',
    diasporaLinks: ['AMS', 'ROT', 'PAR'],
  },
  {
    iso: 'GUF',
    name: 'French Guiana',
    shortName: 'French Guiana',
    capital: 'Cayenne',
    flag: '🇬🇫',
    region: 'Guianas & Mainland Coast',
    x: 910,
    y: 685,
    r: 6.5,
    sovereign: false,
    trendingTag: '#CayenneCarnaval',
    creatorsCount: '2.3K',
    businessesCount: '390',
    eventsCount: '10 Events',
    activeLive: 2,
    summary: 'Guiana Space Centre (Europe’s spaceport), Toulouse-Lautrec mask carnivals, Amazon riverways, and Creole spice gastronomy.',
    diasporaLinks: ['PAR', 'MTL'],
  },

  // ── Global Diaspora Metropolitan Hubs ──
  {
    iso: 'MIA',
    name: 'Miami Diaspora Hub',
    shortName: 'Miami Hub',
    capital: 'Miami, Florida',
    flag: '🇺🇸',
    region: 'Diaspora Hub',
    x: 180,
    y: 90,
    r: 9,
    sovereign: false,
    trendingTag: '#MiamiCarnival',
    creatorsCount: '32.0K',
    businessesCount: '5,800',
    eventsCount: '92 Fetes',
    activeLive: 31,
    summary: 'The primary international gateway to the Caribbean. Wynwood cultural fusions, Little Haiti, Little Havana, and tech trade bridges.',
    diasporaLinks: ['JAM', 'HTI', 'DOM', 'TTO', 'CUB', 'BHS'],
  },
  {
    iso: 'NYC',
    name: 'New York City Diaspora Hub',
    shortName: 'NYC Hub',
    capital: 'New York, New York',
    flag: '🗽',
    region: 'Diaspora Hub',
    x: 290,
    y: 40,
    r: 10,
    sovereign: false,
    trendingTag: '#WestIndianDayParade',
    creatorsCount: '44.0K',
    businessesCount: '7,200',
    eventsCount: '115 Events',
    activeLive: 42,
    summary: 'Brooklyn Eastern Parkway West Indian American Day Parade, Flatbush Little Caribbean, sound system sessions, and media headquarters.',
    diasporaLinks: ['JAM', 'TTO', 'DOM', 'GUY', 'HTI', 'BRB'],
  },
  {
    iso: 'TOR',
    name: 'Toronto Diaspora Hub',
    shortName: 'Toronto Hub',
    capital: 'Toronto, Ontario',
    flag: '🇨🇦',
    region: 'Diaspora Hub',
    x: 220,
    y: 25,
    r: 9,
    sovereign: false,
    trendingTag: '#Caribana2026',
    creatorsCount: '28.5K',
    businessesCount: '4,600',
    eventsCount: '68 Fetes',
    activeLive: 21,
    summary: 'Toronto Caribbean Carnival (Caribana), North America’s largest cultural street festival, Little Jamaica on Eglinton, and culinary markets.',
    diasporaLinks: ['JAM', 'TTO', 'GUY', 'BRB', 'VCT'],
  },
  {
    iso: 'LON',
    name: 'London Diaspora Hub',
    shortName: 'London Hub',
    capital: 'London, England',
    flag: '🇬🇧',
    region: 'Diaspora Hub',
    x: 740,
    y: 50,
    r: 9.5,
    sovereign: false,
    trendingTag: '#NottingHillCarnival',
    creatorsCount: '36.0K',
    businessesCount: '5,100',
    eventsCount: '84 Events',
    activeLive: 27,
    summary: 'Windrush generation legacy, Notting Hill Carnival European epicenter, Brixton markets, sound system culture, and UK publishing.',
    diasporaLinks: ['JAM', 'TTO', 'BRB', 'DMA', 'LCA', 'GRD'],
  },
  {
    iso: 'AMS',
    name: 'Amsterdam Diaspora Hub',
    shortName: 'Amsterdam Hub',
    capital: 'Amsterdam, Netherlands',
    flag: '🇳🇱',
    region: 'Diaspora Hub',
    x: 815,
    y: 65,
    r: 8,
    sovereign: false,
    trendingTag: '#KwakuFestival',
    creatorsCount: '12.4K',
    businessesCount: '1,850',
    eventsCount: '32 Events',
    activeLive: 9,
    summary: 'Kwaku Summer Festival, Bijlmermeer cultural mosaic, Dutch Caribbean connections (Aruba, Curaçao, Bonaire, Suriname, Sint Maarten).',
    diasporaLinks: ['SUR', 'CUW', 'ABW', 'BES', 'SXM'],
  },
  {
    iso: 'PAR',
    name: 'Paris Diaspora Hub',
    shortName: 'Paris Hub',
    capital: 'Paris, France',
    flag: '🇫🇷',
    region: 'Diaspora Hub',
    x: 780,
    y: 105,
    r: 8.5,
    sovereign: false,
    trendingTag: '#CarnavalTropicalParis',
    creatorsCount: '16.8K',
    businessesCount: '2,400',
    eventsCount: '41 Events',
    activeLive: 12,
    summary: 'Carnaval Tropical de Paris on the Champs-Élysées, French West Indian culinary arts, Zouk and Gwo Ka music festivals, and literary salons.',
    diasporaLinks: ['GLP', 'MTQ', 'HTI', 'GUF'],
  },
  {
    iso: 'ATL',
    name: 'Atlanta Diaspora Hub',
    shortName: 'Atlanta Hub',
    capital: 'Atlanta, Georgia',
    flag: '🍑',
    region: 'Diaspora Hub',
    x: 160,
    y: 120,
    r: 7.5,
    sovereign: false,
    trendingTag: '#AtlantaCaribbeanCarnival',
    creatorsCount: '18.2K',
    businessesCount: '2,900',
    eventsCount: '45 Events',
    activeLive: 15,
    summary: 'Atlanta Caribbean Carnival, Decatur culinary scene, sound system producers, and Southern diaspora entrepreneurship.',
    diasporaLinks: ['JAM', 'TTO', 'VIR', 'BHS'],
  },
];

export const CARIBBEAN_GEO_BY_ISO: Record<string, CaribbeanGeoEntity> =
  Object.fromEntries(CARIBBEAN_GEO_ENTITIES.map((e) => [e.iso, e]));
