/**
 * Canonical Caribbean Geospatial Data & Coordinates — Single Source of Truth
 *
 * TUKUBI platform — Caribbean Futurism & Geospatial Discovery Engine.
 * Provides accurate relative coordinates (0-1000 x 0-750 canvas space),
 * political and administrative classifications, regional groupings,
 * cultural descriptions, and deep-link discovery mappings.
 *
 * Political Classification Integrity (Sections 11-16):
 * - Independent Countries
 * - Constituent / Autonomous Countries
 * - Dependent / Overseas Territories
 * - Caribbean Netherlands (Special Municipalities)
 * - Mainland Caribbean (Coastal Regions)
 * - Diaspora Metropolitan Hubs
 */

export type CaribbeanClassification =
  | 'Independent Country'
  | 'Constituent Country'
  | 'Dependent Territory'
  | 'Caribbean Netherlands'
  | 'Mainland Caribbean'
  | 'Diaspora Hub';

export interface CaribbeanGeoEntity {
  iso: string;
  name: string;
  officialName?: string;
  shortName: string;
  capital: string;
  flag: string;
  classification: CaribbeanClassification;
  region:
    | 'Greater Antilles'
    | 'Lesser Antilles (Leeward)'
    | 'Lesser Antilles (Windward)'
    | 'Southern Caribbean & ABC'
    | 'Guianas & Mainland Coast'
    | 'Diaspora Hub';
  subregion?: string;
  languages?: string[];
  currency?: string;
  timezone?: string;
  x: number;
  y: number;
  r: number;
  sovereign: boolean;
  trendingTag: string;
  summary: string;
  diasporaLinks?: string[];
}

export const CARIBBEAN_GEO_ENTITIES: CaribbeanGeoEntity[] = [
  // ── Greater Antilles & Lucayan Archipelago ──
  {
    iso: 'BHS',
    name: 'The Bahamas',
    officialName: 'Commonwealth of The Bahamas',
    shortName: 'Bahamas',
    capital: 'Nassau',
    flag: '🇧🇸',
    classification: 'Independent Country',
    region: 'Greater Antilles',
    subregion: 'Lucayan Archipelago',
    languages: ['English', 'Bahamian Creole'],
    currency: 'BSD ($)',
    timezone: 'UTC-5',
    x: 270,
    y: 190,
    r: 7,
    sovereign: true,
    trendingTag: '#JunkanooVibes',
    summary: 'Junkanoo spectacle, crystal turquoise archipelagos, maritime commerce, and vibrant conch culture.',
    diasporaLinks: ['MIA', 'ATL', 'NYC'],
  },
  {
    iso: 'CUB',
    name: 'Cuba',
    officialName: 'Republic of Cuba',
    shortName: 'Cuba',
    capital: 'Havana',
    flag: '🇨🇺',
    classification: 'Independent Country',
    region: 'Greater Antilles',
    subregion: 'Greater Antilles',
    languages: ['Spanish'],
    currency: 'CUP (₱)',
    timezone: 'UTC-5',
    x: 250,
    y: 280,
    r: 11,
    sovereign: true,
    trendingTag: '#SonCubano',
    summary: 'Son, Rumba, Afro-Cuban jazz, historic colonial architecture, classic automotive art, and literary legacy.',
    diasporaLinks: ['MIA', 'NYC', 'MAD'],
  },
  {
    iso: 'CYM',
    name: 'Cayman Islands',
    officialName: 'Cayman Islands',
    shortName: 'Cayman',
    capital: 'George Town',
    flag: '🇰🇾',
    classification: 'Dependent Territory',
    region: 'Greater Antilles',
    subregion: 'Western Caribbean',
    languages: ['English'],
    currency: 'KYD ($)',
    timezone: 'UTC-5',
    x: 195,
    y: 340,
    r: 5,
    sovereign: false,
    trendingTag: '#CaymanCarnival',
    summary: 'Global financial hub, Batabano carnival, stingray sandbars, and culinary excellence in the Western Caribbean.',
    diasporaLinks: ['MIA', 'LON', 'TOR'],
  },
  {
    iso: 'JAM',
    name: 'Jamaica',
    officialName: 'Jamaica',
    shortName: 'Jamaica',
    capital: 'Kingston',
    flag: '🇯🇲',
    classification: 'Independent Country',
    region: 'Greater Antilles',
    subregion: 'Greater Antilles',
    languages: ['English', 'Jamaican Patois'],
    currency: 'JMD (J$)',
    timezone: 'UTC-5',
    x: 285,
    y: 375,
    r: 9.5,
    sovereign: true,
    trendingTag: '#KingstonVibes',
    summary: 'Heart of Reggae, Dancehall, Sound System culture, Blue Mountain coffee, track & field supremacy, and Jerk cuisine.',
    diasporaLinks: ['NYC', 'MIA', 'TOR', 'LON'],
  },
  {
    iso: 'HTI',
    name: 'Haiti',
    officialName: 'Republic of Haiti',
    shortName: 'Haiti',
    capital: 'Port-au-Prince',
    flag: '🇭🇹',
    classification: 'Independent Country',
    region: 'Greater Antilles',
    subregion: 'Hispaniola',
    languages: ['Haitian Creole', 'French'],
    currency: 'HTG (G)',
    timezone: 'UTC-5',
    x: 375,
    y: 345,
    r: 9,
    sovereign: true,
    trendingTag: '#AyitiArt',
    summary: 'Pioneering republic, vibrant metal and canvas fine art, Kompa rhythms, artisanal coffee, and rich diaspora history.',
    diasporaLinks: ['MIA', 'NYC', 'MTL', 'PAR'],
  },
  {
    iso: 'DOM',
    name: 'Dominican Republic',
    officialName: 'Dominican Republic',
    shortName: 'Dominican Rep.',
    capital: 'Santo Domingo',
    flag: '🇩🇴',
    classification: 'Independent Country',
    region: 'Greater Antilles',
    subregion: 'Hispaniola',
    languages: ['Spanish'],
    currency: 'DOP (RD$)',
    timezone: 'UTC-4',
    x: 440,
    y: 345,
    r: 10,
    sovereign: true,
    trendingTag: '#RDTechSummit',
    summary: 'Bachata, Merengue, artisanal organic cacao, Caribbean tech innovation, historic Zona Colonial, and baseball pride.',
    diasporaLinks: ['NYC', 'MIA', 'BOS', 'MAD'],
  },
  {
    iso: 'TCA',
    name: 'Turks & Caicos Islands',
    officialName: 'Turks and Caicos Islands',
    shortName: 'Turks & Caicos',
    capital: 'Cockburn Town',
    flag: '🇹🇨',
    classification: 'Dependent Territory',
    region: 'Greater Antilles',
    subregion: 'Lucayan Archipelago',
    languages: ['English'],
    currency: 'USD ($)',
    timezone: 'UTC-5',
    x: 420,
    y: 260,
    r: 5.5,
    sovereign: false,
    trendingTag: '#ProvoVibes',
    summary: 'Rake and scrape music, Grace Bay turquoise reefs, luxury ecotourism, and vibrant conch festivals.',
    diasporaLinks: ['MIA', 'NYC', 'TOR'],
  },
  {
    iso: 'PRI',
    name: 'Puerto Rico',
    officialName: 'Commonwealth of Puerto Rico',
    shortName: 'Puerto Rico',
    capital: 'San Juan',
    flag: '🇵🇷',
    classification: 'Dependent Territory',
    region: 'Greater Antilles',
    subregion: 'Greater Antilles',
    languages: ['Spanish', 'English'],
    currency: 'USD ($)',
    timezone: 'UTC-4',
    x: 530,
    y: 360,
    r: 9,
    sovereign: false,
    trendingTag: '#SanJuanNights',
    summary: 'Boricua pride, Salsa and Reggaeton origins, Old San Juan cobblestone arts, culinary fusions, and diaspora bridges.',
    diasporaLinks: ['NYC', 'ORL', 'MIA', 'PHL'],
  },

  // ── Lesser Antilles (Leeward Islands) ──
  {
    iso: 'VIR',
    name: 'US Virgin Islands',
    officialName: 'Virgin Islands of the United States',
    shortName: 'USVI',
    capital: 'Charlotte Amalie',
    flag: '🇻🇮',
    classification: 'Dependent Territory',
    region: 'Lesser Antilles (Leeward)',
    subregion: 'Virgin Islands',
    languages: ['English', 'Virgin Islands Creole'],
    currency: 'USD ($)',
    timezone: 'UTC-4',
    x: 580,
    y: 360,
    r: 5,
    sovereign: false,
    trendingTag: '#StThomasCarnival',
    summary: 'St. Thomas, St. John, and St. Croix heritage, quelbe music, Danish colonial architecture, and carnival pageantry.',
    diasporaLinks: ['ATL', 'MIA', 'NYC'],
  },
  {
    iso: 'VGB',
    name: 'British Virgin Islands',
    officialName: 'British Virgin Islands',
    shortName: 'BVI',
    capital: 'Road Town',
    flag: '🇻🇬',
    classification: 'Dependent Territory',
    region: 'Lesser Antilles (Leeward)',
    subregion: 'Virgin Islands',
    languages: ['English'],
    currency: 'USD ($)',
    timezone: 'UTC-4',
    x: 600,
    y: 355,
    r: 4.5,
    sovereign: false,
    trendingTag: '#TortolaLife',
    summary: 'Sailing capital of the world, The Baths geological wonder, yachting regattas, and fungi music.',
    diasporaLinks: ['LON', 'MIA', 'NYC'],
  },
  {
    iso: 'AIA',
    name: 'Anguilla',
    officialName: 'Anguilla',
    shortName: 'Anguilla',
    capital: 'The Valley',
    flag: '🇦🇮',
    classification: 'Dependent Territory',
    region: 'Lesser Antilles (Leeward)',
    subregion: 'Leeward Islands',
    languages: ['English'],
    currency: 'XCD ($)',
    timezone: 'UTC-4',
    x: 625,
    y: 350,
    r: 4.5,
    sovereign: false,
    trendingTag: '#AnguillaSummerFest',
    summary: 'Tranquil pristine beaches, boat racing national sport, culinary capital status, and lively summer festivals.',
    diasporaLinks: ['LON', 'NYC', 'MIA'],
  },
  {
    iso: 'SXM',
    name: 'Sint Maarten',
    officialName: 'Sint Maarten (Country of the Kingdom of the Netherlands)',
    shortName: 'Sint Maarten',
    capital: 'Philipsburg',
    flag: '🇸🇽',
    classification: 'Constituent Country',
    region: 'Lesser Antilles (Leeward)',
    subregion: 'Leeward Islands',
    languages: ['Dutch', 'English'],
    currency: 'ANG (NAƒ)',
    timezone: 'UTC-4',
    x: 632,
    y: 365,
    r: 5,
    sovereign: false,
    trendingTag: '#SXMCarnival',
    summary: 'The Friendly Island, dual Dutch-French heritage, duty-free shopping, Maho beach, and vibrant Grand Carnival.',
    diasporaLinks: ['AMS', 'PAR', 'MIA'],
  },
  {
    iso: 'MAF',
    name: 'Saint Martin (French Collectivity)',
    officialName: 'Collectivity of Saint Martin',
    shortName: 'Saint Martin',
    capital: 'Marigot',
    flag: '🇲🇫',
    classification: 'Dependent Territory',
    region: 'Lesser Antilles (Leeward)',
    subregion: 'Leeward Islands',
    languages: ['French', 'English'],
    currency: 'EUR (€)',
    timezone: 'UTC-4',
    x: 636,
    y: 356,
    r: 4.5,
    sovereign: false,
    trendingTag: '#MarigotVibes',
    summary: 'French Antillean charm, Marigot waterfront open-air markets, Grand Case culinary strip, and luxury yachting bays.',
    diasporaLinks: ['PAR', 'MTL', 'GLP'],
  },
  {
    iso: 'BLM',
    name: 'Saint Barthélemy',
    officialName: 'Collectivity of Saint Barthélemy',
    shortName: 'St. Barth',
    capital: 'Gustavia',
    flag: '🇧🇱',
    classification: 'Dependent Territory',
    region: 'Lesser Antilles (Leeward)',
    subregion: 'Leeward Islands',
    languages: ['French'],
    currency: 'EUR (€)',
    timezone: 'UTC-4',
    x: 648,
    y: 368,
    r: 4.5,
    sovereign: false,
    trendingTag: '#StBarthLife',
    summary: 'Swedish colonial heritage in Gustavia, world-renowned luxury sailing regattas, pristine coves, and haute gastronomy.',
    diasporaLinks: ['PAR', 'MIA', 'NYC'],
  },
  {
    iso: 'SAB',
    name: 'Saba',
    officialName: 'Public Entity Saba (Caribbean Netherlands)',
    shortName: 'Saba',
    capital: 'The Bottom',
    flag: '🇸🇧',
    classification: 'Caribbean Netherlands',
    region: 'Lesser Antilles (Leeward)',
    subregion: 'SSS Islands',
    languages: ['English', 'Dutch'],
    currency: 'USD ($)',
    timezone: 'UTC-4',
    x: 618,
    y: 382,
    r: 4.5,
    sovereign: false,
    trendingTag: '#UnspoiledQueen',
    summary: 'The Unspoiled Queen, Mount Scenery volcanic summit (highest point of the Kingdom of the Netherlands), and world-class marine diving sanctuaries.',
    diasporaLinks: ['AMS', 'SXM'],
  },
  {
    iso: 'EUX',
    name: 'Sint Eustatius',
    officialName: 'Public Entity Sint Eustatius (Statia)',
    shortName: 'Statia',
    capital: 'Oranjestad',
    flag: '🇧🇶',
    classification: 'Caribbean Netherlands',
    region: 'Lesser Antilles (Leeward)',
    subregion: 'SSS Islands',
    languages: ['English', 'Dutch'],
    currency: 'USD ($)',
    timezone: 'UTC-4',
    x: 624,
    y: 395,
    r: 4.5,
    sovereign: false,
    trendingTag: '#StatiaHistory',
    summary: 'The Golden Rock of Caribbean trade history, First Salute commemoration, Fort Oranje, The Quill crater trails, and rich archaeological dives.',
    diasporaLinks: ['AMS', 'SXM'],
  },
  {
    iso: 'KNA',
    name: 'Saint Kitts & Nevis',
    officialName: 'Federation of Saint Christopher and Nevis',
    shortName: 'St. Kitts & Nevis',
    capital: 'Basseterre',
    flag: '🇰🇳',
    classification: 'Independent Country',
    region: 'Lesser Antilles (Leeward)',
    subregion: 'Leeward Islands',
    languages: ['English'],
    currency: 'XCD ($)',
    timezone: 'UTC-4',
    x: 630,
    y: 408,
    r: 5,
    sovereign: true,
    trendingTag: '#SugarMas',
    summary: 'Sugar Mas carnival, Brimstone Hill fortress UNESCO site, Caribbean music festival, and rainforest peaks.',
    diasporaLinks: ['LON', 'NYC', 'TOR'],
  },
  {
    iso: 'ATG',
    name: 'Antigua & Barbuda',
    officialName: 'Antigua and Barbuda',
    shortName: 'Antigua',
    capital: "St. John's",
    flag: '🇦🇬',
    classification: 'Independent Country',
    region: 'Lesser Antilles (Leeward)',
    subregion: 'Leeward Islands',
    languages: ['English'],
    currency: 'XCD ($)',
    timezone: 'UTC-4',
    x: 662,
    y: 385,
    r: 6,
    sovereign: true,
    trendingTag: '#AntiguaSailingWeek',
    summary: '365 white sand beaches, Antigua Sailing Week, Nelson’s Dockyard maritime history, and sweet Benna music.',
    diasporaLinks: ['LON', 'NYC', 'TOR'],
  },
  {
    iso: 'MSR',
    name: 'Montserrat',
    officialName: 'Montserrat',
    shortName: 'Montserrat',
    capital: 'Brades (de facto)',
    flag: '🇲🇸',
    classification: 'Dependent Territory',
    region: 'Lesser Antilles (Leeward)',
    subregion: 'Leeward Islands',
    languages: ['English'],
    currency: 'XCD ($)',
    timezone: 'UTC-4',
    x: 638,
    y: 422,
    r: 4.5,
    sovereign: false,
    trendingTag: '#EmeraldIsle',
    summary: 'The Emerald Isle of the Caribbean, rich Irish-African cultural blend, Soufrière Hills volcano, and Calypso kings.',
    diasporaLinks: ['LON', 'BHM', 'TOR'],
  },
  {
    iso: 'GLP',
    name: 'Guadeloupe',
    officialName: 'Department of Guadeloupe (French Overseas Region)',
    shortName: 'Guadeloupe',
    capital: 'Basse-Terre',
    flag: '🇬🇵',
    classification: 'Dependent Territory',
    region: 'Lesser Antilles (Leeward)',
    subregion: 'Leeward Islands',
    languages: ['French', 'Guadeloupean Creole'],
    currency: 'EUR (€)',
    timezone: 'UTC-4',
    x: 668,
    y: 435,
    r: 7,
    sovereign: false,
    trendingTag: '#GwokaVibes',
    summary: 'Butterfly archipelago, Gwo Ka drum heritage, Creole gastronomy, La Soufrière volcano hikes, and Zouk music.',
    diasporaLinks: ['PAR', 'MTL', 'MAR'],
  },
  {
    iso: 'DMA',
    name: 'Dominica',
    officialName: 'Commonwealth of Dominica',
    shortName: 'Dominica',
    capital: 'Roseau',
    flag: '🇩🇲',
    classification: 'Independent Country',
    region: 'Lesser Antilles (Leeward)',
    subregion: 'Windward / Leeward Seam',
    languages: ['English', 'Dominican Creole French'],
    currency: 'XCD ($)',
    timezone: 'UTC-4',
    x: 660,
    y: 465,
    r: 5.5,
    sovereign: true,
    trendingTag: '#NatureIsle',
    summary: 'The Nature Island, Boiling Lake geothermal wonder, World Creole Music Festival, and Kalinago indigenous territory.',
    diasporaLinks: ['LON', 'NYC', 'TOR'],
  },

  // ── Lesser Antilles (Windward Islands) ──
  {
    iso: 'MTQ',
    name: 'Martinique',
    officialName: 'Territorial Collectivity of Martinique',
    shortName: 'Martinique',
    capital: 'Fort-de-France',
    flag: '🇲🇶',
    classification: 'Dependent Territory',
    region: 'Lesser Antilles (Windward)',
    subregion: 'Windward Islands',
    languages: ['French', 'Martinican Creole'],
    currency: 'EUR (€)',
    timezone: 'UTC-4',
    x: 668,
    y: 495,
    r: 7,
    sovereign: false,
    trendingTag: '#MartiniqueZouk',
    summary: 'Isle of Flowers, birthplace of Zouk, Tour des Yoles round-island boat race, rum distilleries, and Aimé Césaire poetry.',
    diasporaLinks: ['PAR', 'MTL', 'LYO'],
  },
  {
    iso: 'LCA',
    name: 'Saint Lucia',
    officialName: 'Saint Lucia',
    shortName: 'Saint Lucia',
    capital: 'Castries',
    flag: '🇱🇨',
    classification: 'Independent Country',
    region: 'Lesser Antilles (Windward)',
    subregion: 'Windward Islands',
    languages: ['English', 'Saint Lucian Creole'],
    currency: 'XCD ($)',
    timezone: 'UTC-4',
    x: 665,
    y: 525,
    r: 6.5,
    sovereign: true,
    trendingTag: '#LucianCarnival',
    summary: 'Majestic volcanic Gros and Petit Pitons, Saint Lucia Jazz Festival, sulphur springs, and Dennery Segment soca.',
    diasporaLinks: ['LON', 'NYC', 'TOR'],
  },
  {
    iso: 'BRB',
    name: 'Barbados',
    officialName: 'Republic of Barbados',
    shortName: 'Barbados',
    capital: 'Bridgetown',
    flag: '🇧🇧',
    classification: 'Independent Country',
    region: 'Lesser Antilles (Windward)',
    subregion: 'Barbados (Atlantic Facing)',
    languages: ['English', 'Bajan Creole'],
    currency: 'BBD (Bds$)',
    timezone: 'UTC-4',
    x: 722,
    y: 535,
    r: 7.5,
    sovereign: true,
    trendingTag: '#CropOver2026',
    summary: 'Culinary capital, historic Mount Gay aged rum heritage, Crop Over Grand Kadooment, and Caribbean fintech leadership.',
    diasporaLinks: ['NYC', 'LON', 'TOR', 'MIA'],
  },
  {
    iso: 'VCT',
    name: 'Saint Vincent & the Grenadines',
    officialName: 'Saint Vincent and the Grenadines',
    shortName: 'St. Vincent',
    capital: 'Kingstown',
    flag: '🇻🇨',
    classification: 'Independent Country',
    region: 'Lesser Antilles (Windward)',
    subregion: 'Windward Islands',
    languages: ['English', 'Vincentian Creole'],
    currency: 'XCD ($)',
    timezone: 'UTC-4',
    x: 652,
    y: 555,
    r: 6,
    sovereign: true,
    trendingTag: '#VincyMas',
    summary: 'Vincy Mas festival, 32 idyllic Grenadines isles including Bequia & Mustique, La Soufrière trails, and artisanal yachting.',
    diasporaLinks: ['NYC', 'LON', 'TOR'],
  },
  {
    iso: 'GRD',
    name: 'Grenada',
    officialName: 'State of Grenada',
    shortName: 'Grenada',
    capital: "St. George's",
    flag: '🇬🇩',
    classification: 'Independent Country',
    region: 'Lesser Antilles (Windward)',
    subregion: 'Windward Islands',
    languages: ['English', 'Grenadian Creole'],
    currency: 'XCD ($)',
    timezone: 'UTC-4',
    x: 648,
    y: 588,
    r: 6,
    sovereign: true,
    trendingTag: '#Spicemas',
    summary: 'The Spice Isle of nutmeg and organic cocoa, Spicemas Jab Jab carnival ritual, Grand Anse beach, and underwater sculpture park.',
    diasporaLinks: ['NYC', 'LON', 'TOR'],
  },

  // ── Southern Caribbean & ABC Islands ──
  {
    iso: 'TTO',
    name: 'Trinidad & Tobago',
    officialName: 'Republic of Trinidad and Tobago',
    shortName: 'Trinidad & Tobago',
    capital: 'Port of Spain',
    flag: '🇹🇹',
    classification: 'Independent Country',
    region: 'Southern Caribbean & ABC',
    subregion: 'Continental Shelf / Southern Caribbean',
    languages: ['English', 'Trinidadian Creole'],
    currency: 'TTD (TT$)',
    timezone: 'UTC-4',
    x: 672,
    y: 628,
    r: 9.5,
    sovereign: true,
    trendingTag: '#CarnivalTT',
    summary: 'Birthplace of Steelpan, Soca, Calypso, and the greatest carnival spectacle on earth; diverse culinary doubles and roti culture.',
    diasporaLinks: ['NYC', 'MIA', 'TOR', 'LON', 'HOU'],
  },
  {
    iso: 'ABW',
    name: 'Aruba',
    officialName: 'Country of Aruba (Kingdom of the Netherlands)',
    shortName: 'Aruba',
    capital: 'Oranjestad',
    flag: '🇦🇼',
    classification: 'Constituent Country',
    region: 'Southern Caribbean & ABC',
    subregion: 'ABC Islands',
    languages: ['Papiamento', 'Dutch', 'English', 'Spanish'],
    currency: 'AWG (Afl.)',
    timezone: 'UTC-4',
    x: 420,
    y: 535,
    r: 6,
    sovereign: false,
    trendingTag: '#OneHappyIsland',
    summary: 'One Happy Island, divi-divi trees, desert cactus landscapes alongside turquoise seas, Papiamento language, and festive dande music.',
    diasporaLinks: ['AMS', 'MIA', 'NYC'],
  },
  {
    iso: 'CUW',
    name: 'Curaçao',
    officialName: 'Country of Curaçao (Kingdom of the Netherlands)',
    shortName: 'Curaçao',
    capital: 'Willemstad',
    flag: '🇨🇼',
    classification: 'Constituent Country',
    region: 'Southern Caribbean & ABC',
    subregion: 'ABC Islands',
    languages: ['Papiamentu', 'Dutch', 'English', 'Spanish'],
    currency: 'ANG (NAƒ)',
    timezone: 'UTC-4',
    x: 460,
    y: 545,
    r: 6.5,
    sovereign: false,
    trendingTag: '#WillemstadArt',
    summary: 'UNESCO Willemstad Handelskade waterfront, Curaçao North Sea Jazz festival, blue liqueur heritage, and rich Afro-Caribbean folklore.',
    diasporaLinks: ['AMS', 'MIA', 'NYC'],
  },
  {
    iso: 'BES',
    name: 'Bonaire',
    officialName: 'Public Entity Bonaire (Caribbean Netherlands)',
    shortName: 'Bonaire',
    capital: 'Kralendijk',
    flag: '🇧🇶',
    classification: 'Caribbean Netherlands',
    region: 'Southern Caribbean & ABC',
    subregion: 'ABC Islands',
    languages: ['Papiamentu', 'Dutch'],
    currency: 'USD ($)',
    timezone: 'UTC-4',
    x: 490,
    y: 545,
    r: 5,
    sovereign: false,
    trendingTag: '#DiversParadise',
    summary: 'Diver’s paradise marine sanctuary, pink flamingo salt flats, windsurfing world records at Lac Bay, and tranquil eco-living.',
    diasporaLinks: ['AMS', 'MIA'],
  },

  // ── Guianas & Mainland Caribbean Coast ──
  {
    iso: 'BLZ',
    name: 'Belize',
    officialName: 'Belize',
    shortName: 'Belize',
    capital: 'Belmopan',
    flag: '🇧🇿',
    classification: 'Mainland Caribbean',
    region: 'Guianas & Mainland Coast',
    subregion: 'Central America Caribbean Coast',
    languages: ['English', 'Kriol', 'Spanish'],
    currency: 'BZD (BZ$)',
    timezone: 'UTC-6',
    x: 80,
    y: 320,
    r: 7,
    sovereign: true,
    trendingTag: '#BelizeBarrierReef',
    summary: 'Garifuna drum music, Belize Great Blue Hole barrier reef, ancient Maya temples, and lush tropical jungle biodiversity.',
    diasporaLinks: ['LAX', 'CHI', 'MIA'],
  },
  {
    iso: 'PAN',
    name: 'Panama (Caribbean Coast)',
    officialName: 'Republic of Panama',
    shortName: 'Panama',
    capital: 'Panama City',
    flag: '🇵🇦',
    classification: 'Mainland Caribbean',
    region: 'Guianas & Mainland Coast',
    subregion: 'Central America Isthmus',
    languages: ['Spanish', 'Afro-Antillean English'],
    currency: 'USD / PAB (B/.)',
    timezone: 'UTC-5',
    x: 230,
    y: 590,
    r: 7,
    sovereign: true,
    trendingTag: '#BocasDelToro',
    summary: 'Bocas del Toro archipelago, Afro-Antillean heritage in Colón, Reggae en Español pioneers, and the Panama Canal trade gateway.',
    diasporaLinks: ['MIA', 'NYC', 'ATL'],
  },
  {
    iso: 'COL',
    name: 'Colombia (Caribbean Region)',
    officialName: 'Republic of Colombia (Caribbean Departmental Region)',
    shortName: 'Colombia Coast',
    capital: 'Cartagena / Barranquilla',
    flag: '🇨🇴',
    classification: 'Mainland Caribbean',
    region: 'Guianas & Mainland Coast',
    subregion: 'South American Caribbean Coast',
    languages: ['Spanish'],
    currency: 'COP (COL$)',
    timezone: 'UTC-5',
    x: 310,
    y: 560,
    r: 8,
    sovereign: true,
    trendingTag: '#CarnavalDeBarranquilla',
    summary: 'Barranquilla UNESCO Carnival, historic walled Cartagena, Cumbia rhythms, Palenque Afro-heritage, and coastal arts.',
    diasporaLinks: ['MIA', 'NYC', 'MAD'],
  },
  {
    iso: 'VEN',
    name: 'Venezuela (Caribbean Region)',
    officialName: 'Bolivarian Republic of Venezuela (Caribbean Coast & Islands)',
    shortName: 'Venezuela Coast',
    capital: 'Caracas / La Guaira',
    flag: '🇻🇪',
    classification: 'Mainland Caribbean',
    region: 'Guianas & Mainland Coast',
    subregion: 'South American Caribbean Coast',
    languages: ['Spanish'],
    currency: 'VES (Bs.)',
    timezone: 'UTC-4',
    x: 520,
    y: 615,
    r: 8,
    sovereign: true,
    trendingTag: '#LosRoquesVibes',
    summary: 'Los Roques coral archipelago, Tambor coastal drum traditions, Afro-Caribbean fusion, Paraguaná peninsula, and vibrant maritime heritage.',
    diasporaLinks: ['MIA', 'MAD', 'NYC', 'BOG'],
  },
  {
    iso: 'GUY',
    name: 'Guyana',
    officialName: 'Co-operative Republic of Guyana',
    shortName: 'Guyana',
    capital: 'Georgetown',
    flag: '🇬🇾',
    classification: 'Mainland Caribbean',
    region: 'Guianas & Mainland Coast',
    subregion: 'Guiana Shield',
    languages: ['English', 'Guyanese Creole'],
    currency: 'GYD (G$)',
    timezone: 'UTC-4',
    x: 800,
    y: 660,
    r: 8,
    sovereign: true,
    trendingTag: '#GuyanaMash',
    summary: 'Land of Many Waters, Kaieteur single-drop falls, Mashramani celebration, rainforest conservation, and energy innovation.',
    diasporaLinks: ['NYC', 'TOR', 'LON', 'MIA'],
  },
  {
    iso: 'SUR',
    name: 'Suriname',
    officialName: 'Republic of Suriname',
    shortName: 'Suriname',
    capital: 'Paramaribo',
    flag: '🇸🇷',
    classification: 'Mainland Caribbean',
    region: 'Guianas & Mainland Coast',
    subregion: 'Guiana Shield',
    languages: ['Dutch', 'Sranan Tongo'],
    currency: 'SRD ($)',
    timezone: 'UTC-3',
    x: 860,
    y: 675,
    r: 7.5,
    sovereign: true,
    trendingTag: '#KasekoMusic',
    summary: 'Kaseko music, Paramaribo UNESCO wooden Dutch architecture, Maroon and Javanese heritage, and Amazonian ecotourism.',
    diasporaLinks: ['AMS', 'ROT', 'PAR'],
  },
  {
    iso: 'GUF',
    name: 'French Guiana',
    officialName: 'Department of French Guiana (French Overseas Region)',
    shortName: 'French Guiana',
    capital: 'Cayenne',
    flag: '🇬🇫',
    classification: 'Mainland Caribbean',
    region: 'Guianas & Mainland Coast',
    subregion: 'Guiana Shield',
    languages: ['French', 'Guianese Creole'],
    currency: 'EUR (€)',
    timezone: 'UTC-3',
    x: 910,
    y: 685,
    r: 6.5,
    sovereign: false,
    trendingTag: '#CayenneCarnaval',
    summary: 'Guiana Space Centre (Europe’s spaceport), Toulouse-Lautrec mask carnivals, Amazon riverways, and Creole spice gastronomy.',
    diasporaLinks: ['PAR', 'MTL'],
  },

  // ── Global Diaspora Metropolitan Hubs ──
  {
    iso: 'MIA',
    name: 'Miami Diaspora Hub',
    officialName: 'Miami Greater Caribbean Metropolitan Hub',
    shortName: 'Miami Hub',
    capital: 'Miami, Florida',
    flag: '🇺🇸',
    classification: 'Diaspora Hub',
    region: 'Diaspora Hub',
    subregion: 'North American Hub',
    languages: ['English', 'Spanish', 'Haitian Creole'],
    currency: 'USD ($)',
    timezone: 'UTC-5',
    x: 180,
    y: 90,
    r: 9,
    sovereign: false,
    trendingTag: '#MiamiCarnival',
    summary: 'The primary international gateway to the Caribbean. Wynwood cultural fusions, Little Haiti, Little Havana, and tech trade bridges.',
    diasporaLinks: ['JAM', 'HTI', 'DOM', 'TTO', 'CUB', 'BHS'],
  },
  {
    iso: 'NYC',
    name: 'New York City Diaspora Hub',
    officialName: 'New York City Caribbean Cultural & Media Hub',
    shortName: 'NYC Hub',
    capital: 'New York, New York',
    flag: '🗽',
    classification: 'Diaspora Hub',
    region: 'Diaspora Hub',
    subregion: 'North American Hub',
    languages: ['English', 'Spanish', 'Haitian Creole', 'Patois'],
    currency: 'USD ($)',
    timezone: 'UTC-5',
    x: 290,
    y: 40,
    r: 10,
    sovereign: false,
    trendingTag: '#WestIndianDayParade',
    summary: 'Brooklyn Eastern Parkway West Indian American Day Parade, Flatbush Little Caribbean, sound system sessions, and media headquarters.',
    diasporaLinks: ['JAM', 'TTO', 'DOM', 'GUY', 'HTI', 'BRB'],
  },
  {
    iso: 'TOR',
    name: 'Toronto Diaspora Hub',
    officialName: 'Greater Toronto Caribbean Creative Hub',
    shortName: 'Toronto Hub',
    capital: 'Toronto, Ontario',
    flag: '🇨🇦',
    classification: 'Diaspora Hub',
    region: 'Diaspora Hub',
    subregion: 'North American Hub',
    languages: ['English'],
    currency: 'CAD (CA$)',
    timezone: 'UTC-5',
    x: 220,
    y: 25,
    r: 9,
    sovereign: false,
    trendingTag: '#Caribana2026',
    summary: 'Toronto Caribbean Carnival (Caribana), North America’s largest cultural street festival, Little Jamaica on Eglinton, and culinary markets.',
    diasporaLinks: ['JAM', 'TTO', 'GUY', 'BRB', 'VCT'],
  },
  {
    iso: 'LON',
    name: 'London Diaspora Hub',
    officialName: 'London Caribbean Heritage & Publishing Hub',
    shortName: 'London Hub',
    capital: 'London, England',
    flag: '🇬🇧',
    classification: 'Diaspora Hub',
    region: 'Diaspora Hub',
    subregion: 'European Hub',
    languages: ['English'],
    currency: 'GBP (£)',
    timezone: 'UTC+0',
    x: 740,
    y: 50,
    r: 9.5,
    sovereign: false,
    trendingTag: '#NottingHillCarnival',
    summary: 'Windrush generation legacy, Notting Hill Carnival European epicenter, Brixton markets, sound system culture, and UK publishing.',
    diasporaLinks: ['JAM', 'TTO', 'BRB', 'DMA', 'LCA', 'GRD'],
  },
  {
    iso: 'AMS',
    name: 'Amsterdam Diaspora Hub',
    officialName: 'Amsterdam Dutch Caribbean Gateway',
    shortName: 'Amsterdam Hub',
    capital: 'Amsterdam, Netherlands',
    flag: '🇳🇱',
    classification: 'Diaspora Hub',
    region: 'Diaspora Hub',
    subregion: 'European Hub',
    languages: ['Dutch', 'Papiamento', 'English'],
    currency: 'EUR (€)',
    timezone: 'UTC+1',
    x: 815,
    y: 65,
    r: 8,
    sovereign: false,
    trendingTag: '#KwakuFestival',
    summary: 'Kwaku Summer Festival, Bijlmermeer cultural mosaic, Dutch Caribbean connections (Aruba, Curaçao, Bonaire, Suriname, Sint Maarten).',
    diasporaLinks: ['SUR', 'CUW', 'ABW', 'BES', 'SXM'],
  },
  {
    iso: 'PAR',
    name: 'Paris Diaspora Hub',
    officialName: 'Paris French Antillean Arts & Culture Hub',
    shortName: 'Paris Hub',
    capital: 'Paris, France',
    flag: '🇫🇷',
    classification: 'Diaspora Hub',
    region: 'Diaspora Hub',
    subregion: 'European Hub',
    languages: ['French', 'Creole'],
    currency: 'EUR (€)',
    timezone: 'UTC+1',
    x: 780,
    y: 105,
    r: 8.5,
    sovereign: false,
    trendingTag: '#CarnavalTropicalParis',
    summary: 'Carnaval Tropical de Paris on the Champs-Élysées, French West Indian culinary arts, Zouk and Gwo Ka music festivals, and literary salons.',
    diasporaLinks: ['GLP', 'MTQ', 'HTI', 'GUF'],
  },
  {
    iso: 'ATL',
    name: 'Atlanta Diaspora Hub',
    officialName: 'Atlanta Caribbean Music & Entrepreneurship Hub',
    shortName: 'Atlanta Hub',
    capital: 'Atlanta, Georgia',
    flag: '🍑',
    classification: 'Diaspora Hub',
    region: 'Diaspora Hub',
    subregion: 'North American Hub',
    languages: ['English'],
    currency: 'USD ($)',
    timezone: 'UTC-5',
    x: 160,
    y: 120,
    r: 7.5,
    sovereign: false,
    trendingTag: '#AtlantaCaribbeanCarnival',
    summary: 'Atlanta Caribbean Carnival, Decatur culinary scene, sound system producers, and Southern diaspora entrepreneurship.',
    diasporaLinks: ['JAM', 'TTO', 'VIR', 'BHS'],
  },
];

export const CARIBBEAN_GEO_BY_ISO: Record<string, CaribbeanGeoEntity> =
  Object.fromEntries(CARIBBEAN_GEO_ENTITIES.map((e) => [e.iso, e]));

export const CLASSIFICATION_COLORS: Record<CaribbeanClassification, { bg: string; text: string; border: string; glow: string; badge: string }> = {
  'Independent Country': {
    bg: 'bg-brand-caribbeanSea/20',
    text: 'text-brand-caribbeanSea',
    border: 'border-brand-caribbeanSea/40',
    glow: '#00B4D8',
    badge: 'Independent Country',
  },
  'Constituent Country': {
    bg: 'bg-brand-goldenHour/20',
    text: 'text-brand-goldenHour',
    border: 'border-brand-goldenHour/40',
    glow: '#FFB347',
    badge: 'Constituent Country',
  },
  'Dependent Territory': {
    bg: 'bg-emerald-500/20',
    text: 'text-emerald-400',
    border: 'border-emerald-500/40',
    glow: '#10B981',
    badge: 'Overseas Territory',
  },
  'Caribbean Netherlands': {
    bg: 'bg-orange-500/20',
    text: 'text-orange-400',
    border: 'border-orange-500/40',
    glow: '#F97316',
    badge: 'Caribbean Netherlands',
  },
  'Mainland Caribbean': {
    bg: 'bg-brand-sunriseCoral/20',
    text: 'text-brand-sunriseCoral',
    border: 'border-brand-sunriseCoral/40',
    glow: '#FF7A59',
    badge: 'Mainland Caribbean',
  },
  'Diaspora Hub': {
    bg: 'bg-brand-sunsetPurple/20',
    text: 'text-brand-sunsetPurple',
    border: 'border-brand-sunsetPurple/40',
    glow: '#7B2CBF',
    badge: 'Diaspora Hub',
  },
};
